# ============================================================
# 03_plot_gcvb_interaction_regions.R
#
# Aim
# ---
# Plot predicted mRNA interaction regions along the GcvB sRNA
# sequence using method-specific interaction coordinates generated
# by TargetRNA2, IntaRNA and CopraRNA.
#
# The script uses the harmonised method-level output generated by:
#
#   01_harmonise_target_predictions.R
#
# By default, the annotated prediction set is used:
#
#   target_predictions_method_level_annotated.csv
#
# This contains only predictions associated with an assigned gene
# name after harmonisation.
#
# To plot the complete prediction set instead, change the input
# filename in USER SETTINGS to:
#
#   target_predictions_method_level_all.csv
#
# Repeated loci are retained because each prediction method may
# identify a different interaction region for the same candidate.
#
# Conserved GcvB regions R1 and R2 are highlighted for reference.
#
#
# INPUT
# -----
#
# results/tables/
#   target_predictions_method_level_annotated.csv
#
#
# Expected columns:
#
#   method
#   reference_locus
#   gene
#   srna_start
#   srna_stop
#
#
# OUTPUTS
# -------
#
# results/tables/
#   gcvb_interaction_regions_plot_data.csv
#
# results/figures/
#   gcvb_interaction_regions.pdf
#   gcvb_interaction_regions.tiff
#   gcvb_interaction_regions_preview.png
#
#
# RUNNING THE SCRIPT
# ------------------
#
# 1. Run 01_harmonise_target_predictions.R.
# 2. Check the USER SETTINGS below.
# 3. Run this script from the repository root.
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()

# ------------------------------------------------------------
# Input dataset
# ------------------------------------------------------------

input_filename <-
  "target_predictions_method_level_annotated.csv"


# To use all predictions instead:
#
# input_filename <-
#   "target_predictions_method_level_all.csv"



# ------------------------------------------------------------
# GcvB sequence length
# ------------------------------------------------------------

gcvb_length <- 196



# ------------------------------------------------------------
# Conserved GcvB interaction regions
# ------------------------------------------------------------

r1_start <- 78
r1_stop  <- 90

r2_start <- 137
r2_stop  <- 148



# ------------------------------------------------------------
# Prediction-method colours
# ------------------------------------------------------------

source_colours <- c(
  "CopraRNA"   = "#F8766D",
  "TargetRNA2" = "#7CAE00",
  "IntaRNA"    = "#00BFC4"
)



# ------------------------------------------------------------
# Figure dimensions
# ------------------------------------------------------------

figure_width <- 8.5
figure_height <- 13

figure_dpi <- 600



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "stringr",
  "ggplot2"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  install.packages(missing_pkgs)
}


suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(stringr)
  library(ggplot2)
})



# ============================================================
# PATHS
# ============================================================

project_dir <- getwd()


input_file <- file.path(
  project_dir,
  "results",
  "tables",
  input_filename
)


table_dir <- file.path(
  project_dir,
  "results",
  "tables"
)


figure_dir <- file.path(
  project_dir,
  "results",
  "figures"
)


dir.create(
  table_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


dir.create(
  figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)



# ============================================================
# CHECK INPUT
# ============================================================

if (!file.exists(input_file)) {
  
  stop(
    "Input file not found:\n",
    input_file,
    "\n\nRun 01_harmonise_target_predictions.R first."
  )
}



# ============================================================
# IMPORT HARMONISED PREDICTIONS
# ============================================================

targets <- read_csv(
  input_file,
  show_col_types = FALSE
)



required_columns <- c(
  "method",
  "reference_locus",
  "gene",
  "srna_start",
  "srna_stop"
)


missing_columns <- setdiff(
  required_columns,
  names(targets)
)


if (length(missing_columns) > 0) {
  
  stop(
    "Input table is missing required column(s):\n",
    paste(
      missing_columns,
      collapse = ", "
    )
  )
}



# ============================================================
# PREPARE PLOTTING DATA
# ============================================================

targets_plot <- targets %>%
  
  transmute(
    
    reference_locus =
      as.character(
        reference_locus
      ),
    
    gene =
      as.character(
        gene
      ),
    
    prediction_source =
      as.character(
        method
      ),
    
    gcvb_start =
      suppressWarnings(
        as.numeric(
          srna_start
        )
      ),
    
    gcvb_stop =
      suppressWarnings(
        as.numeric(
          srna_stop
        )
      )
  ) %>%
  
  mutate(
    
    reference_locus =
      str_trim(
        reference_locus
      ),
    
    gene =
      str_trim(
        gene
      ),
    
    prediction_source =
      str_trim(
        prediction_source
      ),
    
    interaction_start =
      pmin(
        gcvb_start,
        gcvb_stop,
        na.rm = FALSE
      ),
    
    interaction_stop =
      pmax(
        gcvb_start,
        gcvb_stop,
        na.rm = FALSE
      )
  )



# ============================================================
# REMOVE INCOMPLETE RECORDS
# ============================================================

targets_plot <- targets_plot %>%
  
  filter(
    !is.na(gene),
    gene != "",
    !is.na(prediction_source),
    prediction_source != "",
    !is.na(interaction_start),
    !is.na(interaction_stop),
    is.finite(interaction_start),
    is.finite(interaction_stop)
  )



# ============================================================
# COORDINATE QC
# ============================================================

outside_range <- targets_plot %>%
  filter(
    interaction_start < 1 |
      interaction_stop > gcvb_length
  )


if (nrow(outside_range) > 0) {
  
  warning(
    nrow(outside_range),
    " interaction(s) fall outside the configured GcvB sequence ",
    "range of 1-",
    gcvb_length,
    " nt."
  )
}



cat(
  "\n============================================\n",
  "GcvB interaction-region plot\n",
  "============================================\n\n",
  sep = ""
)


cat(
  "Input file: ",
  basename(input_file),
  "\n\n",
  sep = ""
)


cat(
  "Method-specific interactions retained: ",
  nrow(targets_plot),
  "\n\n",
  sep = ""
)


cat(
  "Interactions retained by prediction method:\n"
)


print(
  targets_plot %>%
    count(
      prediction_source,
      sort = TRUE
    )
)



# ============================================================
# PREDICTION-METHOD ORDER
# ============================================================

preferred_source_order <- c(
  "CopraRNA",
  "TargetRNA2",
  "IntaRNA"
)


observed_sources <- unique(
  targets_plot$prediction_source
)


source_order <- c(
  
  preferred_source_order[
    preferred_source_order %in%
      observed_sources
  ],
  
  setdiff(
    observed_sources,
    preferred_source_order
  )
)



# Check that colours are available for all observed methods.

missing_colours <- setdiff(
  source_order,
  names(source_colours)
)


if (length(missing_colours) > 0) {
  
  stop(
    "No plotting colour has been defined for:\n",
    paste(
      missing_colours,
      collapse = ", "
    )
  )
}



targets_plot <- targets_plot %>%
  mutate(
    
    prediction_source = factor(
      prediction_source,
      levels = source_order
    )
  )



# ============================================================
# ORDER INTERACTIONS
# ============================================================

row_step <- 0.72


targets_plot <- targets_plot %>%
  arrange(
    prediction_source,
    interaction_start,
    interaction_stop,
    gene,
    reference_locus
  ) %>%
  mutate(
    
    plot_y = rev(
      seq(
        from = 1,
        by = row_step,
        length.out = n()
      )
    )
  )



# ============================================================
# CREATE METHOD BLOCKS
# ============================================================

method_blocks <- targets_plot %>%
  group_by(
    prediction_source
  ) %>%
  summarise(
    
    ymin =
      min(plot_y) -
      (row_step / 2),
    
    ymax =
      max(plot_y) +
      (row_step / 2),
    
    ymid =
      mean(
        c(
          ymin,
          ymax
        )
      ),
    
    .groups =
      "drop"
  ) %>%
  mutate(
    
    method_label =
      as.character(
        prediction_source
      )
  )



# ============================================================
# GENERATE INTERACTION-SITE PLOT
# ============================================================

interaction_plot <- ggplot() +
  
  
  # ----------------------------------------------------------
# Conserved GcvB regions
# ----------------------------------------------------------

annotate(
  "rect",
  xmin = r1_start,
  xmax = r1_stop,
  ymin = -Inf,
  ymax = Inf,
  fill = "#C7352D",
  alpha = 0.06
) +
  
  annotate(
    "rect",
    xmin = r2_start,
    xmax = r2_stop,
    ymin = -Inf,
    ymax = Inf,
    fill = "#C7352D",
    alpha = 0.06
  ) +
  
  
  # ----------------------------------------------------------
# Region boundaries
# ----------------------------------------------------------

annotate(
  "segment",
  x = r1_start,
  xend = r1_start,
  y = -Inf,
  yend = Inf,
  colour = "grey35",
  linewidth = 0.35
) +
  
  annotate(
    "segment",
    x = r1_stop,
    xend = r1_stop,
    y = -Inf,
    yend = Inf,
    colour = "grey35",
    linewidth = 0.35
  ) +
  
  annotate(
    "segment",
    x = r2_start,
    xend = r2_start,
    y = -Inf,
    yend = Inf,
    colour = "grey35",
    linewidth = 0.35
  ) +
  
  annotate(
    "segment",
    x = r2_stop,
    xend = r2_stop,
    y = -Inf,
    yend = Inf,
    colour = "grey35",
    linewidth = 0.35
  ) +
  
  
  # ----------------------------------------------------------
# Predicted interaction regions
# ----------------------------------------------------------

geom_segment(
  data = targets_plot,
  aes(
    x = interaction_start,
    xend = interaction_stop,
    y = plot_y,
    yend = plot_y,
    colour = prediction_source
  ),
  linewidth = 1.25,
  lineend = "butt"
) +
  
  
  # ----------------------------------------------------------
# Prediction-method blocks
# ----------------------------------------------------------

geom_rect(
  data = method_blocks,
  aes(
    xmin = gcvb_length + 3,
    xmax = gcvb_length + 10,
    ymin = ymin,
    ymax = ymax,
    fill = prediction_source
  ),
  inherit.aes = FALSE,
  colour = "grey35",
  linewidth = 0.35
) +
  
  geom_text(
    data = method_blocks,
    aes(
      x = gcvb_length + 6.5,
      y = ymid,
      label = method_label
    ),
    inherit.aes = FALSE,
    angle = 270,
    colour = "white",
    fontface = "bold",
    family = "sans",
    size = 4.0
  ) +
  
  
  # ----------------------------------------------------------
# R1 and R2 labels
# ----------------------------------------------------------

annotate(
  "label",
  x = mean(
    c(
      r1_start,
      r1_stop
    )
  ),
  y =
    max(targets_plot$plot_y) +
    (row_step * 1.6),
  label = "R1",
  fill = "#C7352D",
  colour = "white",
  label.size = 0.25,
  size = 3.5,
  fontface = "bold"
) +
  
  annotate(
    "label",
    x = mean(
      c(
        r2_start,
        r2_stop
      )
    ),
    y =
      max(targets_plot$plot_y) +
      (row_step * 1.6),
    label = "R2",
    fill = "#C7352D",
    colour = "white",
    label.size = 0.25,
    size = 3.5,
    fontface = "bold"
  ) +
  
  
  # ----------------------------------------------------------
# Y axis
# ----------------------------------------------------------

scale_y_continuous(
  
  name = NULL,
  
  breaks =
    targets_plot$plot_y,
  
  labels =
    targets_plot$gene,
  
  limits = c(
    min(targets_plot$plot_y) -
      (row_step * 0.8),
    max(targets_plot$plot_y) +
      (row_step * 2.2)
  ),
  
  expand =
    expansion(
      mult = c(
        0,
        0
      )
    )
) +
  
  
  # ----------------------------------------------------------
# X axis
# ----------------------------------------------------------

scale_x_continuous(
  
  name =
    "Position on GcvB (nt)",
  
  limits = c(
    1,
    gcvb_length + 10
  ),
  
  breaks = c(
    1,
    25,
    50,
    75,
    100,
    125,
    150,
    175,
    gcvb_length
  ),
  
  labels = c(
    "1",
    "25",
    "50",
    "75",
    "100",
    "125",
    "150",
    "175",
    as.character(
      gcvb_length
    )
  ),
  
  expand =
    expansion(
      mult = c(
        0.002,
        0.002
      )
    ),
  
  position =
    "top"
) +
  
  
  # ----------------------------------------------------------
# Colour scales
# ----------------------------------------------------------

scale_colour_manual(
  values =
    source_colours,
  drop =
    TRUE
) +
  
  scale_fill_manual(
    values =
      source_colours,
    drop =
      TRUE
  ) +
  
  
  coord_cartesian(
    clip = "off"
  ) +
  
  
  # ----------------------------------------------------------
# Styling
# ----------------------------------------------------------

theme_grey(
  base_size = 10
) +
  
  theme(
    
    text =
      element_text(
        family = "sans"
      ),
    
    axis.text.y =
      element_text(
        size = 9.6,
        colour = "grey20",
        lineheight = 0.76,
        margin = margin(
          r = 2
        )
      ),
    
    axis.ticks.y =
      element_blank(),
    
    axis.text.x.top =
      element_text(
        size = 9.5,
        colour = "grey15"
      ),
    
    axis.ticks.x.top =
      element_line(
        colour = "grey25",
        linewidth = 0.35
      ),
    
    axis.title.x.top =
      element_text(
        size = 11.5,
        margin = margin(
          b = 8
        )
      ),
    
    axis.text.x.bottom =
      element_blank(),
    
    axis.ticks.x.bottom =
      element_blank(),
    
    axis.title.x.bottom =
      element_blank(),
    
    panel.grid.major.y =
      element_line(
        colour = "white",
        linewidth = 0.40
      ),
    
    panel.grid.minor.y =
      element_blank(),
    
    panel.grid.major.x =
      element_line(
        colour = "white",
        linewidth = 0.40
      ),
    
    panel.grid.minor.x =
      element_blank(),
    
    panel.border =
      element_rect(
        colour = "grey35",
        fill = NA,
        linewidth = 0.55
      ),
    
    legend.position =
      "none",
    
    plot.margin =
      margin(
        t = 5,
        r = 8,
        b = 6,
        l = 5
      )
  )



# ============================================================
# DISPLAY FIGURE
# ============================================================

print(
  interaction_plot
)



# ============================================================
# SAVE PLOTTING DATA
# ============================================================

plot_data_output <- targets_plot %>%
  select(
    reference_locus,
    gene,
    prediction_source,
    interaction_start,
    interaction_stop
  )



plot_data_file <- file.path(
  table_dir,
  "gcvb_interaction_regions_plot_data.csv"
)


write_csv(
  plot_data_output,
  plot_data_file,
  na = ""
)



# ============================================================
# SAVE FIGURES
# ============================================================

pdf_file <- file.path(
  figure_dir,
  "gcvb_interaction_regions.pdf"
)


tiff_file <- file.path(
  figure_dir,
  "gcvb_interaction_regions.tiff"
)


png_file <- file.path(
  figure_dir,
  "gcvb_interaction_regions_preview.png"
)



ggsave(
  filename = pdf_file,
  plot = interaction_plot,
  width = figure_width,
  height = figure_height,
  units = "in",
  limitsize = FALSE
)



ggsave(
  filename = tiff_file,
  plot = interaction_plot,
  width = figure_width,
  height = figure_height,
  units = "in",
  dpi = figure_dpi,
  compression = "lzw",
  limitsize = FALSE
)



ggsave(
  filename = png_file,
  plot = interaction_plot,
  width = figure_width,
  height = figure_height,
  units = "in",
  dpi = 300,
  limitsize = FALSE
)



# ============================================================
# COMPLETION SUMMARY
# ============================================================

cat(
  "\n============================================\n",
  "GcvB interaction-region plot complete\n",
  "============================================\n\n",
  sep = ""
)


cat(
  "Plot data:\n",
  plot_data_file,
  "\n\n",
  sep = ""
)


cat(
  "Figures:\n",
  pdf_file,
  "\n",
  tiff_file,
  "\n",
  png_file,
  "\n",
  sep = ""
)
