# ============================================================
# 05_operon_context.R
#
# Aim
# ---
# Assign Operon-mapper operon context to the harmonised GcvB
# candidate target genes.
#
#
# WORKFLOW
# --------
#
# 1. Import the harmonised candidate target list.
# 2. Add reference genomic coordinates and strand.
# 3. Import Operon-mapper ORF coordinates.
# 4. Parse Operon-mapper predicted operons.
# 5. Order operon members in transcriptional direction.
# 6. Map each candidate gene to an Operon-mapper ORF using:
#       a. exact coordinates + strand;
#       b. >=80% reciprocal coordinate overlap as fallback.
# 7. Assign:
#       - operon ID
#       - operon size
#       - position within operon
#       - first/internal/last role
#       - operon genomic boundaries
#       - first and last ORF
#       - ordered operon member list
#       - previous and next ORF
# 8. Export QC summaries and the downstream operon-context file.
#
#
# IMPORTANT
# ---------
#
# This script describes operon context only.
#
# It does NOT decide the final transcript start or 5' UTR.
# Those decisions should be made later by integrating the
# Operon-mapper context with the TSS evidence from Script 04.
#
#
# OPERON-MAPPER INPUT
# -------------------
#
# Operon predictions should be generated by submitting the
# reference genome to Operon-mapper; the resulting
# "list_of_operons" and "ORFs_coordinates" files are required
# as inputs for this script.
#
#
# INPUTS
# ------
#
# results/tables/target_candidates_annotated.csv
#
# data/reference/reference_gene_coordinates.csv
#
# data/raw/operon_mapper/
#   list_of_operons_*
#   ORFs_coordinates_*
#
#
# OUTPUTS
# -------
#
# results/tables/operon_context.csv
# results/tables/operon_mapper_all_operons.csv
# results/tables/operon_mapper_all_orfs.csv
# results/tables/operon_context_summary.csv
# results/tables/operon_context_qc.csv
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()

candidate_filename <-
  "target_candidates_annotated.csv"


reference_filename <-
  "reference_gene_coordinates.csv"


minimum_overlap <-
  0.80



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "stringr",
  "tibble"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  
  install.packages(
    missing_pkgs
  )
}


suppressPackageStartupMessages({
  
  library(readr)
  library(dplyr)
  library(stringr)
  library(tibble)
  
})



# ============================================================
# PATHS
# ============================================================

project_dir <- getwd()


candidate_file <- file.path(
  project_dir,
  "results",
  "tables",
  candidate_filename
)


reference_file <- file.path(
  project_dir,
  "data",
  "reference",
  reference_filename
)


operon_dir <- file.path(
  project_dir,
  "data",
  "raw",
  "operon_mapper"
)


results_dir <- file.path(
  project_dir,
  "results",
  "tables"
)


dir.create(
  results_dir,
  recursive = TRUE,
  showWarnings = FALSE
)



# ============================================================
# CHECK INPUT PATHS
# ============================================================

if (!file.exists(candidate_file)) {
  
  stop(
    "Candidate file not found:\n",
    candidate_file
  )
}


if (!file.exists(reference_file)) {
  
  stop(
    "Reference coordinate file not found:\n",
    reference_file
  )
}


if (!dir.exists(operon_dir)) {
  
  stop(
    "Operon-mapper directory not found:\n",
    operon_dir
  )
}



# ============================================================
# HELPER: CHECK REQUIRED COLUMNS
# ============================================================

check_columns <- function(
    df,
    required,
    label
) {
  
  missing_columns <- setdiff(
    required,
    names(df)
  )
  
  
  if (length(missing_columns) > 0) {
    
    stop(
      label,
      " is missing required column(s):\n",
      paste(
        missing_columns,
        collapse = ", "
      ),
      "\n\nAvailable columns:\n",
      paste(
        names(df),
        collapse = ", "
      )
    )
  }
}



# ============================================================
# HELPER: LOCATE ONE OPERON-MAPPER FILE
# ============================================================

find_one_file <- function(
    directory,
    pattern,
    label
) {
  
  hits <- list.files(
    directory,
    pattern = pattern,
    full.names = TRUE,
    ignore.case = TRUE
  )
  
  
  if (length(hits) == 0) {
    
    stop(
      "Could not find ",
      label,
      " in:\n",
      directory
    )
  }
  
  
  hits <- hits[
    order(
      nchar(basename(hits)),
      basename(hits)
    )
  ]
  
  
  if (length(hits) > 1) {
    
    warning(
      "Multiple files matched ",
      label,
      ". Using:\n",
      basename(hits[1])
    )
  }
  
  
  message(
    label,
    ": ",
    basename(hits[1])
  )
  
  
  return(hits[1])
}



# ============================================================
# LOCATE OPERON-MAPPER FILES
# ============================================================

operons_file <- find_one_file(
  directory = operon_dir,
  pattern = "^list_of_operons",
  label = "Operon-mapper list_of_operons file"
)


orfs_file <- find_one_file(
  directory = operon_dir,
  pattern = "^ORFs_coordinates",
  label = "Operon-mapper ORFs_coordinates file"
)



# ============================================================
# IMPORT CANDIDATE TARGETS
# ============================================================

candidates <- readr::read_csv(
  candidate_file,
  show_col_types = FALSE
)


check_columns(
  candidates,
  c(
    "reference_locus",
    "gene",
    "annotation"
  ),
  "Candidate table"
)


candidates <- candidates |>
  dplyr::mutate(
    
    reference_locus =
      stringr::str_trim(
        as.character(reference_locus)
      ),
    
    gene =
      stringr::str_trim(
        as.character(gene)
      ),
    
    annotation =
      as.character(annotation)
    
  ) |>
  dplyr::filter(
    !is.na(reference_locus),
    reference_locus != ""
  ) |>
  dplyr::distinct(
    reference_locus,
    .keep_all = TRUE
  )



# ============================================================
# IMPORT REFERENCE COORDINATES
# ============================================================

reference <- readr::read_csv(
  reference_file,
  show_col_types = FALSE
)


check_columns(
  reference,
  c(
    "reference_locus",
    "strand",
    "gene_start",
    "gene_end"
  ),
  "Reference coordinate table"
)


reference <- reference |>
  dplyr::transmute(
    
    reference_locus =
      stringr::str_trim(
        as.character(reference_locus)
      ),
    
    strand =
      stringr::str_trim(
        as.character(strand)
      ),
    
    gene_start =
      suppressWarnings(
        as.integer(gene_start)
      ),
    
    gene_end =
      suppressWarnings(
        as.integer(gene_end)
      )
    
  ) |>
  dplyr::filter(
    !is.na(reference_locus),
    reference_locus != ""
  ) |>
  dplyr::distinct(
    reference_locus,
    .keep_all = TRUE
  )



# ============================================================
# ADD REFERENCE COORDINATES TO TARGETS
# ============================================================

targets_all <- candidates |>
  dplyr::left_join(
    reference,
    by = "reference_locus"
  )



# ============================================================
# IDENTIFY TARGETS WITHOUT REFERENCE COORDINATES
# ============================================================

unmapped_reference <- targets_all |>
  dplyr::filter(
    is.na(strand) |
      is.na(gene_start) |
      is.na(gene_end)
  )


if (nrow(unmapped_reference) > 0) {
  
  warning(
    nrow(unmapped_reference),
    " target(s) lack complete reference coordinates."
  )
}



# ============================================================
# RETAIN TARGETS WITH VALID COORDINATES
# ============================================================

targets <- targets_all |>
  dplyr::filter(
    !is.na(strand),
    !is.na(gene_start),
    !is.na(gene_end)
  ) |>
  dplyr::mutate(
    
    target_left =
      pmin(
        gene_start,
        gene_end
      ),
    
    target_right =
      pmax(
        gene_start,
        gene_end
      ),
    
    target_length =
      target_right -
      target_left +
      1L
  )


if (nrow(targets) == 0) {
  
  stop(
    "No target genes could be mapped to the reference ",
    "coordinate table."
  )
}



# ============================================================
# IMPORT OPERON-MAPPER ORF COORDINATES
# ============================================================

orfs <- readr::read_tsv(
  orfs_file,
  col_names = c(
    "seqname",
    "source",
    "feature",
    "orf_start",
    "orf_end",
    "score",
    "strand",
    "frame",
    "attributes"
  ),
  col_types = readr::cols(
    seqname = readr::col_character(),
    source = readr::col_character(),
    feature = readr::col_character(),
    orf_start = readr::col_integer(),
    orf_end = readr::col_integer(),
    score = readr::col_character(),
    strand = readr::col_character(),
    frame = readr::col_character(),
    attributes = readr::col_character()
  ),
  progress = FALSE,
  show_col_types = FALSE
)



# ============================================================
# PARSE OPERON-MAPPER ORF ATTRIBUTES
# ============================================================

orfs <- orfs |>
  dplyr::mutate(
    
    operonmapper_id =
      stringr::str_match(
        attributes,
        "(?:^|;)ID=([^;]+)"
      )[, 2],
    
    product =
      stringr::str_match(
        attributes,
        "(?:^|;)product=([^;]+)"
      )[, 2],
    
    product =
      stringr::str_replace_all(
        product,
        "_",
        " "
      ),
    
    orf_left =
      pmin(
        orf_start,
        orf_end
      ),
    
    orf_right =
      pmax(
        orf_start,
        orf_end
      ),
    
    orf_length =
      orf_right -
      orf_left +
      1L
  )



# ============================================================
# PARSE list_of_operons
# ============================================================
#
# Format:
#
# Operon IdGene Type COGgene PosLeft postRight Strand Function
#
# followed by:
#
# 1
#     dnaA    CDS ...
#     dnaN    CDS ...
#
# 2
#     sodC    CDS ...
#
# etc.

parse_operons <- function(
    path
) {
  
  lines <- readLines(
    path,
    warn = FALSE,
    encoding = "UTF-8"
  )
  
  
  if (length(lines) == 0) {
    
    stop(
      "Operon file is empty:\n",
      path
    )
  }
  
  
  # Remove header.
  
  lines <- lines[-1]
  
  
  # Remove blank lines.
  
  lines <- lines[
    nzchar(
      trimws(lines)
    )
  ]
  
  
  current_operon <- NA_integer_
  
  out <- list()
  
  k <- 0L
  
  
  for (line in lines) {
    
    z <- trimws(line)
    
    
    # A line containing only an integer defines a new operon.
    
    if (
      grepl(
        "^[0-9]+$",
        z
      )
    ) {
      
      current_operon <-
        as.integer(z)
      
      next
    }
    
    
    fields <- strsplit(
      line,
      "\t",
      fixed = TRUE
    )[[1]]
    
    
    # Remove empty fields introduced by leading tab.
    
    fields <- fields[
      nzchar(fields)
    ]
    
    
    if (length(fields) >= 6) {
      
      k <- k + 1L
      
      
      out[[k]] <- tibble::tibble(
        
        operon_id =
          current_operon,
        
        operonmapper_id =
          fields[1],
        
        feature_type =
          fields[2],
        
        COG =
          fields[3],
        
        pos_left =
          suppressWarnings(
            as.integer(fields[4])
          ),
        
        pos_right =
          suppressWarnings(
            as.integer(fields[5])
          ),
        
        strand =
          fields[6],
        
        function_text =
          if (length(fields) >= 7) {
            
            paste(
              fields[7:length(fields)],
              collapse = "\t"
            )
            
          } else {
            
            NA_character_
          }
      )
    }
  }
  
  
  result <- dplyr::bind_rows(out)
  
  
  if (nrow(result) == 0) {
    
    stop(
      "No operon members could be parsed from:\n",
      path
    )
  }
  
  
  return(result)
}



operon_members <- parse_operons(
  operons_file
)



# ============================================================
# STANDARDISE OPERON COORDINATES
# ============================================================

operon_members <- operon_members |>
  dplyr::mutate(
    
    operon_member_left =
      pmin(
        pos_left,
        pos_right
      ),
    
    operon_member_right =
      pmax(
        pos_left,
        pos_right
      )
  )



# ============================================================
# ORDER MEMBERS IN TRANSCRIPTIONAL DIRECTION
# ============================================================
#
# + strand:
#
#   lower coordinate -> higher coordinate
#
# - strand:
#
#   higher coordinate -> lower coordinate

operon_members <- operon_members |>
  dplyr::mutate(
    
    transcription_order_coordinate =
      dplyr::case_when(
        
        strand == "+" ~
          operon_member_left,
        
        strand == "-" ~
          -operon_member_right,
        
        TRUE ~
          NA_real_
      )
  ) |>
  dplyr::group_by(
    operon_id
  ) |>
  dplyr::arrange(
    transcription_order_coordinate,
    .by_group = TRUE
  ) |>
  dplyr::mutate(
    
    operon_size =
      dplyr::n(),
    
    operon_position =
      dplyr::row_number(),
    
    operon_role =
      dplyr::case_when(
        
        operon_size == 1L ~
          "single",
        
        operon_position == 1L ~
          "first",
        
        operon_position == operon_size ~
          "last",
        
        TRUE ~
          "internal"
      ),
    
    previous_orf =
      dplyr::lag(
        operonmapper_id
      ),
    
    next_orf =
      dplyr::lead(
        operonmapper_id
      ),
    
    operon_first_orf =
      dplyr::first(
        operonmapper_id
      ),
    
    operon_last_orf =
      dplyr::last(
        operonmapper_id
      ),
    
    operon_left =
      min(
        operon_member_left,
        na.rm = TRUE
      ),
    
    operon_right =
      max(
        operon_member_right,
        na.rm = TRUE
      ),
    
    operon_members_ordered =
      paste(
        operonmapper_id,
        collapse = ";"
      )
    
  ) |>
  dplyr::ungroup() |>
  dplyr::select(
    -transcription_order_coordinate
  )



# ============================================================
# JOIN OPERON INFORMATION TO ORF TABLE
# ============================================================

orfs_with_operon <- orfs |>
  dplyr::left_join(
    
    operon_members |>
      dplyr::select(
        
        operonmapper_id,
        
        operon_id,
        operon_size,
        operon_position,
        operon_role,
        
        previous_orf,
        next_orf,
        
        operon_first_orf,
        operon_last_orf,
        
        operon_left,
        operon_right,
        
        operon_members_ordered
      ),
    
    by = "operonmapper_id"
  )



# ============================================================
# EXACT TARGET -> ORF MAPPING
# ============================================================
#
# Match on:
#
#   strand
#   target left coordinate
#   target right coordinate
#
# The many-to-many relationship is intentional at this stage
# because all same-strand ORFs are initially compared before
# exact coordinate filtering.

exact_candidates <- dplyr::inner_join(
  targets,
  orfs_with_operon,
  by = "strand",
  relationship = "many-to-many"
) |>
  dplyr::filter(
    target_left == orf_left,
    target_right == orf_right
  )



# ============================================================
# RESOLVE EXACT-MATCH DUPLICATES
# ============================================================

exact <- exact_candidates |>
  dplyr::group_by(
    reference_locus
  ) |>
  dplyr::arrange(
    operonmapper_id,
    .by_group = TRUE
  ) |>
  dplyr::mutate(
    match_rank =
      dplyr::row_number()
  ) |>
  dplyr::filter(
    match_rank == 1L
  ) |>
  dplyr::ungroup() |>
  dplyr::mutate(
    
    mapping_method =
      "exact_coordinates",
    
    mapping_overlap =
      1
  )



# ============================================================
# TARGETS WITHOUT EXACT MATCH
# ============================================================

unmatched <- targets |>
  dplyr::anti_join(
    exact |>
      dplyr::select(
        reference_locus
      ),
    by = "reference_locus"
  )



# ============================================================
# FALLBACK COORDINATE-OVERLAP MAPPING
# ============================================================
#
# Require at least 80% overlap relative to BOTH:
#
#   target length
#   Operon-mapper ORF length
#
# The minimum of these two fractions is used.

fallback_candidates <- dplyr::inner_join(
  unmatched,
  orfs_with_operon,
  by = "strand",
  relationship = "many-to-many"
) |>
  dplyr::mutate(
    
    overlap_bp =
      pmax(
        0L,
        pmin(
          target_right,
          orf_right
        ) -
          pmax(
            target_left,
            orf_left
          ) +
          1L
      ),
    
    overlap_target =
      overlap_bp /
      target_length,
    
    overlap_orf =
      overlap_bp /
      orf_length,
    
    minimum_reciprocal_overlap =
      pmin(
        overlap_target,
        overlap_orf
      ),
    
    coordinate_difference =
      abs(
        target_left -
          orf_left
      ) +
      abs(
        target_right -
          orf_right
      )
  ) |>
  dplyr::filter(
    minimum_reciprocal_overlap >=
      minimum_overlap
  )



# ============================================================
# SELECT BEST FALLBACK MATCH
# ============================================================

fallback <- fallback_candidates |>
  dplyr::group_by(
    reference_locus
  ) |>
  dplyr::arrange(
    
    dplyr::desc(
      minimum_reciprocal_overlap
    ),
    
    coordinate_difference,
    
    operonmapper_id,
    
    .by_group = TRUE
  ) |>
  dplyr::mutate(
    match_rank =
      dplyr::row_number()
  ) |>
  dplyr::filter(
    match_rank == 1L
  ) |>
  dplyr::ungroup() |>
  dplyr::mutate(
    
    mapping_method =
      "coordinate_overlap",
    
    mapping_overlap =
      minimum_reciprocal_overlap
  )



# ============================================================
# COMBINE MAPPED TARGETS
# ============================================================

mapped <- dplyr::bind_rows(
  exact,
  fallback
)



# ============================================================
# TARGETS UNMAPPED TO OPERON-MAPPER ORFs
# ============================================================

unmapped_operonmapper <- targets |>
  dplyr::anti_join(
    mapped |>
      dplyr::select(
        reference_locus
      ),
    by = "reference_locus"
  )



# ============================================================
# CREATE PLACEHOLDER ROWS FOR UNMAPPED TARGETS
# ============================================================

unmapped_rows <- unmapped_operonmapper |>
  dplyr::mutate(
    
    seqname =
      NA_character_,
    
    source =
      NA_character_,
    
    feature =
      NA_character_,
    
    orf_start =
      NA_integer_,
    
    orf_end =
      NA_integer_,
    
    score =
      NA_character_,
    
    frame =
      NA_character_,
    
    attributes =
      NA_character_,
    
    operonmapper_id =
      NA_character_,
    
    product =
      NA_character_,
    
    orf_left =
      NA_integer_,
    
    orf_right =
      NA_integer_,
    
    orf_length =
      NA_integer_,
    
    operon_id =
      NA_integer_,
    
    operon_size =
      NA_integer_,
    
    operon_position =
      NA_integer_,
    
    operon_role =
      NA_character_,
    
    previous_orf =
      NA_character_,
    
    next_orf =
      NA_character_,
    
    operon_first_orf =
      NA_character_,
    
    operon_last_orf =
      NA_character_,
    
    operon_left =
      NA_integer_,
    
    operon_right =
      NA_integer_,
    
    operon_members_ordered =
      NA_character_,
    
    mapping_method =
      "unmapped",
    
    mapping_overlap =
      NA_real_
  )



# ============================================================
# COMBINE ALL TARGETS
# ============================================================

target_operons <- dplyr::bind_rows(
  mapped,
  unmapped_rows
)



# ============================================================
# DEFINE OPERON STATUS
# ============================================================

target_operons <- target_operons |>
  dplyr::mutate(
    
    operon_status =
      dplyr::case_when(
        
        mapping_method == "unmapped" ~
          "Unmapped",
        
        is.na(operon_id) ~
          "No operon assignment",
        
        operon_size == 1L ~
          "Single-gene operon",
        
        operon_role == "first" ~
          "First gene in polycistronic operon",
        
        operon_role == "internal" ~
          "Internal gene in polycistronic operon",
        
        operon_role == "last" ~
          "Last gene in polycistronic operon",
        
        TRUE ~
          "Review"
      ),
    
    
    internal_polycistronic =
      dplyr::case_when(
        
        operon_size > 1L &
          operon_role %in%
          c(
            "internal",
            "last"
          ) ~
          
          TRUE,
        
        operon_size >= 1L ~
          
          FALSE,
        
        TRUE ~
          
          NA
      ),
    
    
    first_gene_in_operon =
      dplyr::case_when(
        
        operon_role %in%
          c(
            "first",
            "single"
          ) ~
          
          TRUE,
        
        operon_role %in%
          c(
            "internal",
            "last"
          ) ~
          
          FALSE,
        
        TRUE ~
          
          NA
      ),
    
    
    mapping_review_flag =
      dplyr::case_when(
        
        mapping_method ==
          "coordinate_overlap" ~
          
          "review_coordinate_overlap",
        
        mapping_method ==
          "unmapped" ~
          
          "unmapped_to_OperonMapper_ORF",
        
        TRUE ~
          
          ""
      )
  )



# ============================================================
# SELECT FINAL DOWNSTREAM COLUMNS
# ============================================================

operon_context <- target_operons |>
  dplyr::select(
    
    reference_locus,
    gene,
    annotation,
    
    strand,
    gene_start,
    gene_end,
    
    operonmapper_id,
    product,
    
    operon_id,
    operon_size,
    operon_position,
    operon_role,
    operon_status,
    
    first_gene_in_operon,
    internal_polycistronic,
    
    operon_left,
    operon_right,
    
    operon_first_orf,
    operon_last_orf,
    operon_members_ordered,
    
    previous_orf,
    next_orf,
    
    orf_left,
    orf_right,
    
    mapping_method,
    mapping_overlap,
    mapping_review_flag
  ) |>
  dplyr::arrange(
    reference_locus
  )



# ============================================================
# OPERON STATUS SUMMARY
# ============================================================

status_summary <- operon_context |>
  dplyr::group_by(
    operon_status
  ) |>
  dplyr::summarise(
    n_targets =
      dplyr::n(),
    .groups = "drop"
  ) |>
  dplyr::arrange(
    dplyr::desc(
      n_targets
    )
  )



# ============================================================
# MAPPING METHOD SUMMARY
# ============================================================

mapping_summary <- operon_context |>
  dplyr::group_by(
    mapping_method
  ) |>
  dplyr::summarise(
    n_targets =
      dplyr::n(),
    .groups = "drop"
  ) |>
  dplyr::arrange(
    dplyr::desc(
      n_targets
    )
  )



# ============================================================
# QC SUMMARY
# ============================================================

qc_summary <- tibble::tibble(
  
  metric = c(
    
    "candidate_loci_input",
    
    "candidate_loci_with_reference_coordinates",
    
    "candidate_loci_without_reference_coordinates",
    
    "OperonMapper_ORFs",
    
    "OperonMapper_operons",
    
    "targets_exact_coordinate_mapping",
    
    "targets_coordinate_overlap_mapping",
    
    "targets_unmapped",
    
    "targets_in_single_gene_operons",
    
    "targets_first_in_polycistronic_operon",
    
    "targets_internal_in_polycistronic_operon",
    
    "targets_last_in_polycistronic_operon"
  ),
  
  
  value = c(
    
    nrow(candidates),
    
    nrow(targets),
    
    nrow(unmapped_reference),
    
    nrow(orfs),
    
    dplyr::n_distinct(
      operon_members$operon_id
    ),
    
    sum(
      operon_context$mapping_method ==
        "exact_coordinates",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$mapping_method ==
        "coordinate_overlap",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$mapping_method ==
        "unmapped",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$operon_status ==
        "Single-gene operon",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$operon_status ==
        "First gene in polycistronic operon",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$operon_status ==
        "Internal gene in polycistronic operon",
      na.rm = TRUE
    ),
    
    sum(
      operon_context$operon_status ==
        "Last gene in polycistronic operon",
      na.rm = TRUE
    )
  )
)



# ============================================================
# OUTPUT FILES
# ============================================================

operon_context_file <- file.path(
  results_dir,
  "operon_context.csv"
)


all_operons_file <- file.path(
  results_dir,
  "operon_mapper_all_operons.csv"
)


all_orfs_file <- file.path(
  results_dir,
  "operon_mapper_all_orfs.csv"
)


status_summary_file <- file.path(
  results_dir,
  "operon_context_summary.csv"
)


mapping_summary_file <- file.path(
  results_dir,
  "operon_mapping_summary.csv"
)


qc_file <- file.path(
  results_dir,
  "operon_context_qc.csv"
)



# ============================================================
# EXPORT
# ============================================================

readr::write_csv(
  operon_context,
  operon_context_file,
  na = ""
)


readr::write_csv(
  operon_members,
  all_operons_file,
  na = ""
)


readr::write_csv(
  orfs_with_operon,
  all_orfs_file,
  na = ""
)


readr::write_csv(
  status_summary,
  status_summary_file,
  na = ""
)


readr::write_csv(
  mapping_summary,
  mapping_summary_file,
  na = ""
)


readr::write_csv(
  qc_summary,
  qc_file,
  na = ""
)



# ============================================================
# CONSOLE SUMMARY
# ============================================================

cat(
  "\n",
  "============================================\n",
  "Operon-context analysis complete\n",
  "============================================\n\n",
  sep = ""
)


cat(
  "Candidate loci imported: ",
  nrow(candidates),
  "\n",
  sep = ""
)


cat(
  "Candidate loci with reference coordinates: ",
  nrow(targets),
  "\n",
  sep = ""
)


cat(
  "Operon-mapper ORFs imported: ",
  nrow(orfs),
  "\n",
  sep = ""
)


cat(
  "Operons parsed: ",
  dplyr::n_distinct(
    operon_members$operon_id
  ),
  "\n\n",
  sep = ""
)


cat(
  "Mapping methods:\n"
)


print(
  mapping_summary
)


cat(
  "\nOperon status:\n"
)


print(
  status_summary
)


cat(
  "\nMain downstream file:\n",
  operon_context_file,
  "\n\n",
  sep = ""
)


cat(
  "QC file:\n",
  qc_file,
  "\n",
  sep = ""
)

