# ============================================================
# 06_integrate_transcript_context.R
#
# Aim
# ---
# Integrate:
#
#   1. TSS consensus evidence
#   2. Operon-mapper context
#   3. Method-specific GcvB-mRNA interaction coordinates
#
# for the harmonised GcvB candidate target set.
#
#
# WORKFLOW
# --------
#
# 1. Import TSS consensus generated by Script 04.
# 2. Import operon context generated by Script 05.
# 3. Import method-level interaction predictions generated by
#    Script 01.
# 4. Merge TSS and operon evidence at gene level.
# 5. Determine whether a selected local TSS can reasonably
#    define the gene's 5' UTR:
#
#       - single-gene operon:
#           local TSS may define the transcript 5' boundary
#
#       - first gene in polycistronic operon:
#           local TSS may define the operon 5' boundary
#
#       - internal/last gene in polycistronic operon:
#           local TSS is retained as evidence for a possible
#           internal/alternative transcript start but is NOT
#           automatically treated as the definitive operon UTR
#
# 6. Standardise each predicted mRNA interaction interval
#    relative to the translation start.
# 7. Reconstruct genomic interaction coordinates.
# 8. Classify each interaction as:
#
#       - 5' UTR
#       - candidate internal 5' UTR
#       - overlaps start codon
#       - CDS
#       - upstream of selected TSS
#       - upstream unresolved
#
# 9. Generate QC and summary tables.
#
#
# IMPORTANT INTERPRETATION
# ------------------------
#
# A local TSS upstream of an internal or last gene in a predicted
# polycistronic operon may represent:
#
#   - an alternative/internal promoter;
#   - a condition-specific transcript;
#   - or a TSS associated with transcriptional complexity.
#
# Therefore these calls are preserved, but are distinguished from
# operon-start TSS assignments.
#
#
# INPUTS
# ------
#
# results/tables/tss_consensus.csv
#
# results/tables/operon_context.csv
#
# results/tables/target_predictions_method_level_annotated.csv
#
#
# OUTPUTS
# -------
#
# results/tables/transcript_context.csv
#
# results/tables/
#   target_interactions_transcript_context.csv
#
# results/tables/
#   target_interactions_figure_input.csv
#
# results/tables/
#   transcript_context_summary.csv
#
# results/tables/
#   binding_context_summary.csv
#
# results/tables/
#   transcript_context_qc.csv
#
# results/tables/
#   prediction_statistics_qc.csv
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()

tss_filename <-
  "tss_consensus.csv"


operon_filename <-
  "operon_context.csv"


prediction_filename <-
  "target_predictions_method_level_annotated.csv"

# The next variables are extracted from the previous scritps and used for QC

expected_candidate_count <-
  96L


expected_interaction_count <-
  122L


prediction_methods <- c(
  "CopraRNA",
  "IntaRNA",
  "TargetRNA2"
)



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "stringr",
  "tibble"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  
  install.packages(
    missing_pkgs
  )
}


suppressPackageStartupMessages({
  
  library(readr)
  library(dplyr)
  library(stringr)
  library(tibble)
  
})



# ============================================================
# PATHS
# ============================================================

project_dir <- getwd()


results_dir <- file.path(
  project_dir,
  "results",
  "tables"
)


tss_file <- file.path(
  results_dir,
  tss_filename
)


operon_file <- file.path(
  results_dir,
  operon_filename
)


prediction_file <- file.path(
  results_dir,
  prediction_filename
)



# ============================================================
# CHECK INPUT FILES
# ============================================================

required_files <- c(
  tss_file,
  operon_file,
  prediction_file
)


missing_files <- required_files[
  !file.exists(required_files)
]


if (length(missing_files) > 0) {
  
  stop(
    "Required input file(s) not found:\n",
    paste(
      missing_files,
      collapse = "\n"
    )
  )
}



# ============================================================
# HELPER: CHECK REQUIRED COLUMNS
# ============================================================

check_columns <- function(
    df,
    required,
    label
) {
  
  missing_columns <- setdiff(
    required,
    names(df)
  )
  
  
  if (length(missing_columns) > 0) {
    
    stop(
      label,
      " is missing required column(s):\n",
      paste(
        missing_columns,
        collapse = ", "
      ),
      "\n\nAvailable columns:\n",
      paste(
        names(df),
        collapse = ", "
      )
    )
  }
}



# ============================================================
# IMPORT TSS CONSENSUS
# ============================================================

tss <- readr::read_csv(
  tss_file,
  show_col_types = FALSE
)


check_columns(
  tss,
  c(
    "reference_locus",
    "gene",
    "annotation",
    "strand",
    "gene_start",
    "gene_end",
    "translation_start",
    "WT_plate_TSS",
    "WT_broth_TSS",
    "TSS_difference",
    "TSS_support",
    "representative_TSS",
    "UTR5_length",
    "representative_TSS_rel_start",
    "multiple_proximal_TSS"
  ),
  "TSS consensus table"
)


tss <- tss |>
  dplyr::mutate(
    
    reference_locus =
      stringr::str_trim(
        as.character(reference_locus)
      ),
    
    gene =
      stringr::str_trim(
        as.character(gene)
      ),
    
    strand =
      stringr::str_trim(
        as.character(strand)
      ),
    
    gene_start =
      as.integer(gene_start),
    
    gene_end =
      as.integer(gene_end),
    
    translation_start =
      as.integer(translation_start),
    
    representative_TSS =
      as.integer(representative_TSS),
    
    UTR5_length =
      as.integer(UTR5_length),
    
    representative_TSS_rel_start =
      as.integer(
        representative_TSS_rel_start
      )
  )



# ============================================================
# IMPORT OPERON CONTEXT
# ============================================================

operon <- readr::read_csv(
  operon_file,
  show_col_types = FALSE
)


check_columns(
  operon,
  c(
    "reference_locus",
    "operon_id",
    "operon_size",
    "operon_position",
    "operon_role",
    "operon_status",
    "first_gene_in_operon",
    "internal_polycistronic",
    "operon_left",
    "operon_right",
    "operon_first_orf",
    "operon_last_orf",
    "operon_members_ordered",
    "mapping_method"
  ),
  "Operon context table"
)


operon <- operon |>
  dplyr::mutate(
    
    reference_locus =
      stringr::str_trim(
        as.character(reference_locus)
      )
  )



# ============================================================
# CHECK GENE-LEVEL UNIQUENESS
# ============================================================

if (
  dplyr::n_distinct(
    tss$reference_locus
  ) != nrow(tss)
) {
  
  stop(
    "Duplicate reference_locus values detected in ",
    "tss_consensus.csv."
  )
}


if (
  dplyr::n_distinct(
    operon$reference_locus
  ) != nrow(operon)
) {
  
  stop(
    "Duplicate reference_locus values detected in ",
    "operon_context.csv."
  )
}



# ============================================================
# CHECK CANDIDATE UNIVERSES
# ============================================================

tss_only <- setdiff(
  tss$reference_locus,
  operon$reference_locus
)


operon_only <- setdiff(
  operon$reference_locus,
  tss$reference_locus
)


if (length(tss_only) > 0) {
  
  warning(
    "Loci present in TSS table but absent from operon table:\n",
    paste(
      tss_only,
      collapse = ", "
    )
  )
}


if (length(operon_only) > 0) {
  
  warning(
    "Loci present in operon table but absent from TSS table:\n",
    paste(
      operon_only,
      collapse = ", "
    )
  )
}


if (nrow(tss) != expected_candidate_count) {
  
  warning(
    "Expected ",
    expected_candidate_count,
    " candidate loci but TSS table contains ",
    nrow(tss),
    "."
  )
}



# ============================================================
# SELECT OPERON COLUMNS FOR INTEGRATION
# ============================================================

operon_for_join <- operon |>
  dplyr::select(
    
    reference_locus,
    
    operonmapper_id,
    product,
    
    operon_id,
    operon_size,
    operon_position,
    operon_role,
    operon_status,
    
    first_gene_in_operon,
    internal_polycistronic,
    
    operon_left,
    operon_right,
    
    operon_first_orf,
    operon_last_orf,
    operon_members_ordered,
    
    previous_orf,
    next_orf,
    
    mapping_method,
    mapping_overlap,
    mapping_review_flag
  )



# ============================================================
# MERGE TSS + OPERON CONTEXT
# ============================================================

transcript_context <- tss |>
  dplyr::left_join(
    operon_for_join,
    by = "reference_locus"
  )



# ============================================================
# CLASSIFY TSS / OPERON RELATIONSHIP
# ============================================================

transcript_context <- transcript_context |>
  dplyr::mutate(
    
    has_representative_TSS =
      !is.na(
        representative_TSS
      ),
    
    
    operon_start_compatible =
      dplyr::case_when(
        
        operon_role %in%
          c(
            "single",
            "first"
          ) ~
          
          TRUE,
        
        operon_role %in%
          c(
            "internal",
            "last"
          ) ~
          
          FALSE,
        
        TRUE ~
          
          NA
      ),
    
    
    transcript_context_class =
      dplyr::case_when(
        
        operon_role == "single" &
          has_representative_TSS ~
          
          "Single_gene_with_local_TSS",
        
        
        operon_role == "first" &
          has_representative_TSS ~
          
          "Operon_first_gene_with_local_TSS",
        
        
        operon_role == "internal" &
          has_representative_TSS ~
          
          "Internal_gene_with_local_TSS_candidate",
        
        
        operon_role == "last" &
          has_representative_TSS ~
          
          "Last_gene_with_local_TSS_candidate",
        
        
        operon_role == "single" &
          !has_representative_TSS ~
          
          "Single_gene_without_representative_TSS",
        
        
        operon_role == "first" &
          !has_representative_TSS ~
          
          "Operon_first_gene_without_representative_TSS",
        
        
        operon_role == "internal" &
          !has_representative_TSS ~
          
          "Internal_gene_without_local_TSS",
        
        
        operon_role == "last" &
          !has_representative_TSS ~
          
          "Last_gene_without_local_TSS",
        
        
        TRUE ~
          
          "Unresolved"
      )
  )



# ============================================================
# DEFINE OPERON-AWARE UTR INTERPRETATION
# ============================================================
#
# local_UTR5_length:
#
#   Distance from the Script 04 representative local TSS to
#   the translation start, regardless of operon position.
#
#
# operon_aware_UTR5_length:
#
#   Assigned only when the target is:
#
#       - a single-gene operon; or
#       - the first gene in a polycistronic operon.
#
#   For internal/last genes, the local TSS is retained but
#   interpreted as a possible internal transcript start.

transcript_context <- transcript_context |>
  dplyr::mutate(
    
    local_UTR5_length =
      UTR5_length,
    
    
    operon_aware_UTR5_length =
      dplyr::case_when(
        
        operon_start_compatible &
          has_representative_TSS ~
          
          UTR5_length,
        
        TRUE ~
          
          NA_integer_
      ),
    
    
    UTR_interpretation =
      dplyr::case_when(
        
        operon_start_compatible &
          has_representative_TSS ~
          
          "Defined_from_operon_compatible_local_TSS",
        
        
        !operon_start_compatible &
          has_representative_TSS ~
          
          "Candidate_internal_transcript_5UTR",
        
        
        !has_representative_TSS &
          TSS_support == "Both_discordant" ~
          
          "Unresolved_discordant_TSS_calls",
        
        
        !has_representative_TSS &
          TSS_support == "No_proximal_TSS" ~
          
          "No_proximal_TSS_detected",
        
        
        TRUE ~
          
          "Unresolved"
      )
  )



# ============================================================
# TRANSCRIPT-CONTEXT REVIEW FLAGS
# ============================================================

transcript_context <- transcript_context |>
  dplyr::mutate(
    
    transcript_review_flag =
      dplyr::case_when(
        
        mapping_method !=
          "exact_coordinates" ~
          
          "review_operon_mapping",
        
        
        TSS_support ==
          "Both_discordant" ~
          
          "discordant_plate_broth_TSS",
        
        
        multiple_proximal_TSS &
          !operon_start_compatible ~
          
          "multiple_TSS_internal_operon_gene",
        
        
        multiple_proximal_TSS ~
          
          "multiple_proximal_TSS",
        
        
        !operon_start_compatible &
          has_representative_TSS ~
          
          "possible_internal_promoter",
        
        
        TSS_support ==
          "No_proximal_TSS" ~
          
          "no_proximal_TSS",
        
        
        TRUE ~
          
          ""
      )
  )



# ============================================================
# IMPORT METHOD-LEVEL PREDICTIONS
# ============================================================

predictions_raw <- readr::read_csv(
  prediction_file,
  show_col_types = FALSE
)


check_columns(
  predictions_raw,
  c(
    "method",
    "reference_locus",
    "gene",
    "annotation",
    "p_value",
    "fdr",
    "combined_p_value",
    "energy",
    "mrna_start",
    "mrna_stop",
    "srna_start",
    "srna_stop",
    "source_file"
  ),
  "Method-level prediction table"
)



# ============================================================
# STANDARDISE PREDICTIONS
# ============================================================

predictions <- predictions_raw |>
  dplyr::transmute(
    
    prediction_index =
      if (
        "index" %in%
        names(predictions_raw)
      ) {
        
        suppressWarnings(
          as.integer(index)
        )
        
      } else {
        
        dplyr::row_number()
      },
    
    
    method =
      stringr::str_trim(
        as.character(method)
      ),
    
    
    rank =
      if (
        "rank" %in%
        names(predictions_raw)
      ) {
        
        suppressWarnings(
          as.numeric(rank)
        )
        
      } else {
        
        NA_real_
      },
    
    
    reference_locus =
      stringr::str_trim(
        as.character(reference_locus)
      ),
    
    
    prediction_gene =
      if (
        "prediction_gene" %in%
        names(predictions_raw)
      ) {
        
        stringr::str_trim(
          as.character(
            prediction_gene
          )
        )
        
      } else {
        
        NA_character_
      },
    
    
    gene =
      stringr::str_trim(
        as.character(gene)
      ),
    
    
    annotation =
      as.character(annotation),
    
    
    p_value =
      suppressWarnings(
        as.numeric(p_value)
      ),
    
    
    fdr =
      suppressWarnings(
        as.numeric(fdr)
      ),
    
    
    combined_p_value =
      suppressWarnings(
        as.numeric(
          combined_p_value
        )
      ),
    
    
    energy =
      suppressWarnings(
        as.numeric(energy)
      ),
    
    
    mrna_start =
      suppressWarnings(
        as.integer(mrna_start)
      ),
    
    
    mrna_stop =
      suppressWarnings(
        as.integer(mrna_stop)
      ),
    
    
    srna_start =
      suppressWarnings(
        as.integer(srna_start)
      ),
    
    
    srna_stop =
      suppressWarnings(
        as.integer(srna_stop)
      ),
    
    
    source_file =
      as.character(source_file)
  ) |>
  
  dplyr::filter(
    method %in%
      prediction_methods
  )



# ============================================================
# CHECK INTERACTION COUNT
# ============================================================

if (
  nrow(predictions) !=
  expected_interaction_count
) {
  
  warning(
    "Expected ",
    expected_interaction_count,
    " method-specific interactions but found ",
    nrow(predictions),
    "."
  )
}



# ============================================================
# CHECK PREDICTION LOCI AGAINST TARGET UNIVERSE
# ============================================================

prediction_not_in_targets <- setdiff(
  predictions$reference_locus,
  transcript_context$reference_locus
)


targets_without_prediction <- setdiff(
  transcript_context$reference_locus,
  predictions$reference_locus
)


if (
  length(
    prediction_not_in_targets
  ) > 0
) {
  
  warning(
    "Prediction loci absent from the candidate universe:\n",
    paste(
      prediction_not_in_targets,
      collapse = ", "
    )
  )
}


if (
  length(
    targets_without_prediction
  ) > 0
) {
  
  warning(
    "Candidate loci with no method-level interaction row:\n",
    paste(
      targets_without_prediction,
      collapse = ", "
    )
  )
}



# ============================================================
# PREDICTION STATISTICS QC
# ============================================================
#
# Conventional probabilities / p-values should lie between
# zero and one.
#
# Missing values are permitted where a prediction method does
# not report that statistic.

prediction_statistics_qc <- predictions |>
  dplyr::mutate(
    
    invalid_p_value =
      !is.na(p_value) &
      (
        p_value < 0 |
          p_value > 1
      ),
    
    
    invalid_fdr =
      !is.na(fdr) &
      (
        fdr < 0 |
          fdr > 1
      ),
    
    
    invalid_combined_p =
      !is.na(
        combined_p_value
      ) &
      (
        combined_p_value < 0 |
          combined_p_value > 1
      ),
    
    
    missing_mRNA_coordinates =
      is.na(mrna_start) |
      is.na(mrna_stop),
    
    
    missing_sRNA_coordinates =
      is.na(srna_start) |
      is.na(srna_stop)
  ) |>
  
  dplyr::filter(
    
    invalid_p_value |
      invalid_fdr |
      invalid_combined_p |
      missing_mRNA_coordinates |
      missing_sRNA_coordinates
  )



# ============================================================
# NORMALISE INTERACTION INTERVALS
# ============================================================
#
# Some tools report the first interaction coordinate as the
# numerically larger value.
#
# Therefore:
#
#   binding_left  = minimum mRNA-relative coordinate
#   binding_right = maximum mRNA-relative coordinate
#
# Translation start = 0.
#
# Negative values are upstream of the start codon.

predictions <- predictions |>
  dplyr::mutate(
    
    binding_left =
      pmin(
        mrna_start,
        mrna_stop,
        na.rm = FALSE
      ),
    
    
    binding_right =
      pmax(
        mrna_start,
        mrna_stop,
        na.rm = FALSE
      ),
    
    
    srna_binding_left =
      pmin(
        srna_start,
        srna_stop,
        na.rm = FALSE
      ),
    
    
    srna_binding_right =
      pmax(
        srna_start,
        srna_stop,
        na.rm = FALSE
      )
  )



# ============================================================
# ADD TRANSCRIPT CONTEXT TO EACH INTERACTION
# ============================================================

interaction_context <- predictions |>
  dplyr::left_join(
    
    transcript_context |>
      dplyr::select(
        
        reference_locus,
        
        strand,
        gene_start,
        gene_end,
        translation_start,
        
        WT_plate_TSS,
        WT_broth_TSS,
        TSS_difference,
        TSS_support,
        
        representative_TSS,
        representative_TSS_rel_start,
        local_UTR5_length,
        operon_aware_UTR5_length,
        
        multiple_proximal_TSS,
        
        operon_id,
        operon_size,
        operon_position,
        operon_role,
        operon_status,
        
        operon_start_compatible,
        transcript_context_class,
        UTR_interpretation,
        transcript_review_flag
      ),
    
    by = "reference_locus"
  )



# ============================================================
# RECONSTRUCT GENOMIC INTERACTION COORDINATES
# ============================================================
#
# + strand:
#
#   genomic coordinate =
#       translation_start + relative position
#
#
# - strand:
#
#   genomic coordinate =
#       translation_start - relative position
#
#
# We retain the unordered endpoints and the left/right genomic
# interval.

interaction_context <- interaction_context |>
  dplyr::mutate(
    
    genomic_binding_coord_1 =
      dplyr::case_when(
        
        strand == "+" ~
          
          translation_start +
          mrna_start,
        
        
        strand == "-" ~
          
          translation_start -
          mrna_start,
        
        
        TRUE ~
          
          NA_integer_
      ),
    
    
    genomic_binding_coord_2 =
      dplyr::case_when(
        
        strand == "+" ~
          
          translation_start +
          mrna_stop,
        
        
        strand == "-" ~
          
          translation_start -
          mrna_stop,
        
        
        TRUE ~
          
          NA_integer_
      ),
    
    
    genomic_binding_left =
      pmin(
        genomic_binding_coord_1,
        genomic_binding_coord_2,
        na.rm = FALSE
      ),
    
    
    genomic_binding_right =
      pmax(
        genomic_binding_coord_1,
        genomic_binding_coord_2,
        na.rm = FALSE
      )
  )



# ============================================================
# BASIC POSITION RELATIVE TO TRANSLATION START
# ============================================================

interaction_context <- interaction_context |>
  dplyr::mutate(
    
    binding_position_basic =
      dplyr::case_when(
        
        is.na(binding_left) |
          is.na(binding_right) ~
          
          "missing_coordinates",
        
        
        binding_left <= 0 &
          binding_right >= 0 ~
          
          "overlaps_start_codon",
        
        
        binding_right < 0 ~
          
          "upstream_of_translation_start",
        
        
        binding_left > 0 ~
          
          "CDS",
        
        
        TRUE ~
          
          "other"
      )
  )



# ============================================================
# TRANSCRIPT-AWARE BINDING CLASSIFICATION
# ============================================================
#
# For upstream interactions:
#
# FIRST / SINGLE GENE
# -------------------
#
# If a representative TSS exists:
#
#   binding entirely between TSS and start codon
#       -> 5UTR
#
#   binding entirely upstream of TSS
#       -> upstream_of_selected_TSS
#
#   binding spans selected TSS
#       -> overlaps_selected_TSS
#
#
# INTERNAL / LAST GENE
# --------------------
#
# A local TSS is treated as evidence for a possible internal
# transcript, not automatically as the primary operon TSS.
#
# Equivalent categories therefore use the term
# "candidate_internal".

interaction_context <- interaction_context |>
  dplyr::mutate(
    
    binding_context =
      dplyr::case_when(
        
        binding_position_basic ==
          "missing_coordinates" ~
          
          "missing_coordinates",
        
        
        binding_position_basic ==
          "overlaps_start_codon" ~
          
          "overlaps_start_codon",
        
        
        binding_position_basic ==
          "CDS" ~
          
          "CDS",
        
        
        # ----------------------------------------------------
        # Single / first operon gene with representative TSS
        # ----------------------------------------------------
        
        binding_right < 0 &
          operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_left >=
          representative_TSS_rel_start ~
          
          "5UTR",
        
        
        binding_right < 0 &
          operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_right <
          representative_TSS_rel_start ~
          
          "upstream_of_selected_TSS",
        
        
        binding_right < 0 &
          operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_left <
          representative_TSS_rel_start &
          binding_right >=
          representative_TSS_rel_start ~
          
          "overlaps_selected_TSS",
        
        
        # ----------------------------------------------------
        # Internal / last operon gene with local TSS
        # ----------------------------------------------------
        
        binding_right < 0 &
          !operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_left >=
          representative_TSS_rel_start ~
          
          "candidate_internal_5UTR",
        
        
        binding_right < 0 &
          !operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_right <
          representative_TSS_rel_start ~
          
          "upstream_of_local_internal_TSS",
        
        
        binding_right < 0 &
          !operon_start_compatible &
          !is.na(
            representative_TSS_rel_start
          ) &
          binding_left <
          representative_TSS_rel_start &
          binding_right >=
          representative_TSS_rel_start ~
          
          "overlaps_local_internal_TSS",
        
        
        # ----------------------------------------------------
        # No representative TSS
        # ----------------------------------------------------
        
        binding_right < 0 &
          is.na(
            representative_TSS_rel_start
          ) ~
          
          "upstream_unresolved",
        
        
        TRUE ~
          
          "other"
      )
  )



# ============================================================
# BINDING REVIEW FLAGS
# ============================================================

interaction_context <- interaction_context |>
  dplyr::mutate(
    
    binding_upstream_of_selected_TSS =
      binding_context %in%
      c(
        "upstream_of_selected_TSS",
        "upstream_of_local_internal_TSS"
      ),
    
    
    binding_review_flag =
      dplyr::case_when(
        
        binding_context ==
          "upstream_of_selected_TSS" ~
          
          "binding_precedes_operon_compatible_TSS",
        
        
        binding_context ==
          "upstream_of_local_internal_TSS" ~
          
          "binding_precedes_local_internal_TSS",
        
        
        binding_context ==
          "candidate_internal_5UTR" ~
          
          "internal_operon_gene_local_TSS",
        
        
        binding_context ==
          "overlaps_local_internal_TSS" ~
          
          "binding_overlaps_local_internal_TSS",
        
        
        binding_context ==
          "upstream_unresolved" ~
          
          "upstream_binding_without_representative_TSS",
        
        
        TSS_support ==
          "Both_discordant" ~
          
          "discordant_TSS_context",
        
        
        TRUE ~
          
          ""
      )
  )



# ============================================================
# METHOD-LEVEL DUPLICATE QC
# ============================================================

duplicate_interactions <- interaction_context |>
  dplyr::group_by(
    
    reference_locus,
    method,
    mrna_start,
    mrna_stop,
    srna_start,
    srna_stop
  ) |>
  
  dplyr::summarise(
    
    n =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::filter(
    n > 1
  )



# ============================================================
# GENE-LEVEL BINDING FLAGS
# ============================================================

binding_gene_summary <- interaction_context |>
  dplyr::group_by(
    reference_locus
  ) |>
  
  dplyr::summarise(
    
    n_method_level_interactions =
      dplyr::n(),
    
    
    n_prediction_methods =
      dplyr::n_distinct(
        method
      ),
    
    
    any_5UTR_binding =
      any(
        binding_context ==
          "5UTR",
        na.rm = TRUE
      ),
    
    
    any_candidate_internal_5UTR_binding =
      any(
        binding_context ==
          "candidate_internal_5UTR",
        na.rm = TRUE
      ),
    
    
    any_start_codon_overlap =
      any(
        binding_context ==
          "overlaps_start_codon",
        na.rm = TRUE
      ),
    
    
    any_CDS_binding =
      any(
        binding_context ==
          "CDS",
        na.rm = TRUE
      ),
    
    
    any_binding_upstream_of_TSS =
      any(
        binding_upstream_of_selected_TSS,
        na.rm = TRUE
      ),
    
    
    .groups =
      "drop"
  )



# ============================================================
# ADD BINDING SUMMARY TO GENE-LEVEL CONTEXT
# ============================================================

transcript_context <- transcript_context |>
  dplyr::left_join(
    binding_gene_summary,
    by = "reference_locus"
  ) |>
  
  dplyr::mutate(
    
    n_method_level_interactions =
      dplyr::coalesce(
        n_method_level_interactions,
        0L
      ),
    
    
    n_prediction_methods =
      dplyr::coalesce(
        n_prediction_methods,
        0L
      ),
    
    
    any_5UTR_binding =
      dplyr::coalesce(
        any_5UTR_binding,
        FALSE
      ),
    
    
    any_candidate_internal_5UTR_binding =
      dplyr::coalesce(
        any_candidate_internal_5UTR_binding,
        FALSE
      ),
    
    
    any_start_codon_overlap =
      dplyr::coalesce(
        any_start_codon_overlap,
        FALSE
      ),
    
    
    any_CDS_binding =
      dplyr::coalesce(
        any_CDS_binding,
        FALSE
      ),
    
    
    any_binding_upstream_of_TSS =
      dplyr::coalesce(
        any_binding_upstream_of_TSS,
        FALSE
      )
  )



# ============================================================
# FINAL GENE-LEVEL COLUMN ORDER
# ============================================================

transcript_context_final <- transcript_context |>
  dplyr::select(
    
    reference_locus,
    gene,
    annotation,
    
    strand,
    gene_start,
    gene_end,
    translation_start,
    
    TSS_support,
    WT_plate_TSS,
    WT_broth_TSS,
    TSS_difference,
    
    representative_TSS,
    representative_TSS_rel_start,
    
    local_UTR5_length,
    operon_aware_UTR5_length,
    
    multiple_proximal_TSS,
    
    operon_id,
    operon_size,
    operon_position,
    operon_role,
    operon_status,
    
    operon_start_compatible,
    
    operon_left,
    operon_right,
    operon_first_orf,
    operon_last_orf,
    operon_members_ordered,
    
    transcript_context_class,
    UTR_interpretation,
    transcript_review_flag,
    
    n_method_level_interactions,
    n_prediction_methods,
    
    any_5UTR_binding,
    any_candidate_internal_5UTR_binding,
    any_start_codon_overlap,
    any_CDS_binding,
    any_binding_upstream_of_TSS
  ) |>
  
  dplyr::arrange(
    reference_locus
  )



# ============================================================
# FINAL METHOD-LEVEL INTERACTION TABLE
# ============================================================

interaction_context_final <- interaction_context |>
  dplyr::select(
    
    prediction_index,
    
    reference_locus,
    gene,
    annotation,
    
    method,
    rank,
    
    p_value,
    fdr,
    combined_p_value,
    energy,
    
    strand,
    gene_start,
    gene_end,
    translation_start,
    
    mrna_start,
    mrna_stop,
    binding_left,
    binding_right,
    
    srna_start,
    srna_stop,
    srna_binding_left,
    srna_binding_right,
    
    genomic_binding_coord_1,
    genomic_binding_coord_2,
    genomic_binding_left,
    genomic_binding_right,
    
    TSS_support,
    representative_TSS,
    representative_TSS_rel_start,
    
    local_UTR5_length,
    operon_aware_UTR5_length,
    
    operon_id,
    operon_size,
    operon_position,
    operon_role,
    
    transcript_context_class,
    
    binding_position_basic,
    binding_context,
    
    binding_upstream_of_selected_TSS,
    binding_review_flag,
    
    source_file
  ) |>
  
  dplyr::arrange(
    
    reference_locus,
    method,
    binding_left
  )



# ============================================================
# FIGURE-READY TABLE
# ============================================================
#
# Translation start = 0.
#
# This table is intentionally compact for plotting binding
# intervals relative to the start codon and local TSS.

figure_input <- interaction_context_final |>
  dplyr::transmute(
    
    reference_locus,
    gene,
    
    method,
    
    strand,
    
    TSS_support,
    
    operon_role,
    
    transcript_context_class,
    
    representative_TSS_rel_start,
    
    local_UTR5_length,
    
    operon_aware_UTR5_length,
    
    binding_left,
    binding_right,
    
    srna_binding_left,
    srna_binding_right,
    
    binding_context
  )



# ============================================================
# TRANSCRIPT-CONTEXT SUMMARY
# ============================================================

transcript_context_summary <- transcript_context_final |>
  dplyr::group_by(
    transcript_context_class
  ) |>
  
  dplyr::summarise(
    
    n_targets =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::arrange(
    dplyr::desc(
      n_targets
    )
  )



# ============================================================
# UTR INTERPRETATION SUMMARY
# ============================================================

utr_summary <- transcript_context |>
  dplyr::group_by(
    UTR_interpretation
  ) |>
  
  dplyr::summarise(
    
    n_targets =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::arrange(
    dplyr::desc(
      n_targets
    )
  )



# ============================================================
# BINDING-CONTEXT SUMMARY
# ============================================================

binding_context_summary <- interaction_context_final |>
  dplyr::group_by(
    binding_context
  ) |>
  
  dplyr::summarise(
    
    n_interactions =
      dplyr::n(),
    
    n_genes =
      dplyr::n_distinct(
        reference_locus
      ),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::arrange(
    dplyr::desc(
      n_interactions
    )
  )



# ============================================================
# PREDICTION METHOD SUMMARY
# ============================================================

prediction_method_summary <- interaction_context_final |>
  dplyr::group_by(
    method
  ) |>
  
  dplyr::summarise(
    
    n_interactions =
      dplyr::n(),
    
    n_genes =
      dplyr::n_distinct(
        reference_locus
      ),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::arrange(
    method
  )



# ============================================================
# NUMBER OF METHODS SUPPORTING EACH GENE
# ============================================================

method_support_summary <- interaction_context_final |>
  dplyr::distinct(
    reference_locus,
    method
  ) |>
  
  dplyr::group_by(
    reference_locus
  ) |>
  
  dplyr::summarise(
    
    n_methods =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::group_by(
    n_methods
  ) |>
  
  dplyr::summarise(
    
    n_genes =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  
  dplyr::arrange(
    n_methods
  )



# ============================================================
# PIPELINE QC SUMMARY
# ============================================================

qc_summary <- tibble::tibble(
  
  metric = c(
    
    "candidate_loci_TSS",
    
    "candidate_loci_operon",
    
    "candidate_loci_integrated",
    
    "method_level_interactions",
    
    "unique_prediction_loci",
    
    "interactions_CopraRNA",
    
    "interactions_IntaRNA",
    
    "interactions_TargetRNA2",
    
    "genes_operon_compatible_with_local_TSS",
    
    "genes_internal_or_last_with_local_TSS",
    
    "genes_without_representative_TSS",
    
    "defined_operon_aware_5UTRs",
    
    "candidate_internal_transcript_5UTRs",
    
    "interactions_classified_5UTR",
    
    "interactions_candidate_internal_5UTR",
    
    "interactions_overlapping_start_codon",
    
    "interactions_CDS",
    
    "interactions_upstream_of_TSS",
    
    "prediction_statistics_QC_rows",
    
    "duplicate_method_level_interactions"
  ),
  
  
  value = c(
    
    nrow(tss),
    
    nrow(operon),
    
    nrow(
      transcript_context_final
    ),
    
    nrow(
      interaction_context_final
    ),
    
    dplyr::n_distinct(
      interaction_context_final$
        reference_locus
    ),
    
    sum(
      interaction_context_final$
        method ==
        "CopraRNA",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        method ==
        "IntaRNA",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        method ==
        "TargetRNA2",
      na.rm = TRUE
    ),
    
    sum(
      transcript_context$
        operon_start_compatible &
        transcript_context$
        has_representative_TSS,
      na.rm = TRUE
    ),
    
    sum(
      !transcript_context$
        operon_start_compatible &
        transcript_context$
        has_representative_TSS,
      na.rm = TRUE
    ),
    
    sum(
      !transcript_context$
        has_representative_TSS,
      na.rm = TRUE
    ),
    
    sum(
      !is.na(
        transcript_context$
          operon_aware_UTR5_length
      )
    ),
    
    sum(
      transcript_context$
        UTR_interpretation ==
        "Candidate_internal_transcript_5UTR",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        binding_context ==
        "5UTR",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        binding_context ==
        "candidate_internal_5UTR",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        binding_context ==
        "overlaps_start_codon",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        binding_context ==
        "CDS",
      na.rm = TRUE
    ),
    
    sum(
      interaction_context_final$
        binding_upstream_of_selected_TSS,
      na.rm = TRUE
    ),
    
    nrow(
      prediction_statistics_qc
    ),
    
    nrow(
      duplicate_interactions
    )
  )
)



# ============================================================
# OUTPUT FILES
# ============================================================

transcript_context_file <- file.path(
  results_dir,
  "transcript_context.csv"
)


interaction_file <- file.path(
  results_dir,
  "target_interactions_transcript_context.csv"
)


figure_file <- file.path(
  results_dir,
  "target_interactions_figure_input.csv"
)


transcript_summary_file <- file.path(
  results_dir,
  "transcript_context_summary.csv"
)


utr_summary_file <- file.path(
  results_dir,
  "utr_interpretation_summary.csv"
)


binding_summary_file <- file.path(
  results_dir,
  "binding_context_summary.csv"
)


prediction_method_summary_file <- file.path(
  results_dir,
  "prediction_method_summary.csv"
)


method_support_summary_file <- file.path(
  results_dir,
  "prediction_method_support_summary.csv"
)


qc_file <- file.path(
  results_dir,
  "transcript_context_qc.csv"
)


statistics_qc_file <- file.path(
  results_dir,
  "prediction_statistics_qc.csv"
)


duplicate_file <- file.path(
  results_dir,
  "duplicate_interactions_qc.csv"
)



# ============================================================
# EXPORT
# ============================================================

readr::write_csv(
  transcript_context_final,
  transcript_context_file,
  na = ""
)


readr::write_csv(
  interaction_context_final,
  interaction_file,
  na = ""
)


readr::write_csv(
  figure_input,
  figure_file,
  na = ""
)


readr::write_csv(
  transcript_context_summary,
  transcript_summary_file,
  na = ""
)


readr::write_csv(
  utr_summary,
  utr_summary_file,
  na = ""
)


readr::write_csv(
  binding_context_summary,
  binding_summary_file,
  na = ""
)


readr::write_csv(
  prediction_method_summary,
  prediction_method_summary_file,
  na = ""
)


readr::write_csv(
  method_support_summary,
  method_support_summary_file,
  na = ""
)


readr::write_csv(
  qc_summary,
  qc_file,
  na = ""
)


readr::write_csv(
  prediction_statistics_qc,
  statistics_qc_file,
  na = ""
)


readr::write_csv(
  duplicate_interactions,
  duplicate_file,
  na = ""
)



# ============================================================
# CONSOLE REPORT
# ============================================================

cat(
  "\n",
  "============================================\n",
  "Transcript-context integration complete\n",
  "============================================\n\n",
  sep = ""
)


cat(
  "Candidate loci integrated: ",
  nrow(
    transcript_context_final
  ),
  "\n",
  sep = ""
)


cat(
  "Method-level interactions integrated: ",
  nrow(
    interaction_context_final
  ),
  "\n\n",
  sep = ""
)



cat(
  "Interactions by prediction method:\n"
)


print(
  prediction_method_summary
)



cat(
  "\nGenes by number of supporting methods:\n"
)


print(
  method_support_summary
)



cat(
  "\nTranscript context:\n"
)


print(
  transcript_context_summary
)



cat(
  "\nUTR interpretation:\n"
)


print(
  utr_summary
)



cat(
  "\nBinding context:\n"
)


print(
  binding_context_summary
)



cat(
  "\nPrediction-statistics QC rows: ",
  nrow(
    prediction_statistics_qc
  ),
  "\n",
  sep = ""
)


cat(
  "Duplicate method-level interaction rows: ",
  nrow(
    duplicate_interactions
  ),
  "\n\n",
  sep = ""
)



cat(
  "Main outputs:\n",
  transcript_context_file,
  "\n",
  interaction_file,
  "\n",
  figure_file,
  "\n",
  qc_file,
  "\n\n",
  sep = ""
)

