# ============================================================
# 07_plot_transcript_relative_interactions.R
#
# Aim
# ---
# Plot predicted sRNA-mRNA interaction sites relative to the
# target CDS start, together with experimentally supported
# transcript start site (TSS) information.
#
#
# This script uses the integrated transcript-context output
# generated by Script 06.
#
#
# FIGURE CONTENT
# --------------
#
# Each row represents one method-specific predicted interaction.
#
# Interaction intervals are shown relative to the translation
# start:
#
#     negative coordinates = upstream / 5' region
#     0                    = CDS start
#     positive coordinates = coding sequence
#
# TSS evidence is shown as vertical ticks:
#
#     filled black tick = concordant WT plate + broth TSS
#     open black tick   = TSS detected in one condition only
#
# TSS-discordant and unresolved calls are not plotted as
# representative TSS markers because Script 04 deliberately
# does not assign a representative coordinate to them.
#
#
# INPUT
# -----
#
# results/tables/
#   target_interactions_transcript_context.csv
#
#
# OUTPUTS
# -------
#
# results/figures/
#   transcript_relative_interactions.pdf
#   transcript_relative_interactions.png
#
# results/tables/
#   transcript_relative_interactions_plotting_data.csv
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()


input_file <-
  "results/tables/target_interactions_transcript_context.csv"


figure_dir <-
  "results/figures"


plotting_data_file <-
  "results/tables/transcript_relative_interactions_plotting_data.csv"


pdf_file <-
  "results/figures/transcript_relative_interactions.pdf"


png_file <-
  "results/figures/transcript_relative_interactions.png"


# Displayed upstream limit.

plot_x_min <-
  -500


# Minimum displayed downstream limit.

minimum_plot_x_max <-
  100



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "ggplot2",
  "stringr",
  "tibble"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  
  install.packages(
    missing_pkgs
  )
}


suppressPackageStartupMessages({
  
  library(readr)
  library(dplyr)
  library(ggplot2)
  library(stringr)
  library(tibble)
  
})



# ============================================================
# CREATE OUTPUT DIRECTORY
# ============================================================

dir.create(
  figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)



# ============================================================
# CHECK INPUT
# ============================================================

if (!file.exists(input_file)) {
  
  stop(
    "Input file not found:\n",
    input_file,
    "\n\nRun Script 06 first."
  )
}



# ============================================================
# READ INTEGRATED INTERACTION TABLE
# ============================================================

binding <- readr::read_csv(
  input_file,
  show_col_types = FALSE
)



# ============================================================
# CHECK REQUIRED COLUMNS
# ============================================================

required_cols <- c(
  
  "reference_locus",
  "gene",
  
  "method",
  
  "binding_left",
  "binding_right",
  
  "TSS_support",
  "representative_TSS_rel_start",
  
  "operon_role",
  "binding_context"
)


missing_cols <- setdiff(
  required_cols,
  names(binding)
)


if (length(missing_cols) > 0) {
  
  stop(
    "Input table is missing required column(s):\n",
    paste(
      missing_cols,
      collapse = ", "
    )
  )
}



# ============================================================
# STANDARDISE PREDICTION-METHOD LABELS
# ============================================================

binding <- binding |>
  dplyr::mutate(
    
    method =
      dplyr::case_when(
        
        stringr::str_detect(
          method,
          stringr::regex(
            "TargetRNA",
            ignore_case = TRUE
          )
        ) ~
          
          "TargetRNA2",
        
        
        stringr::str_detect(
          method,
          stringr::regex(
            "IntaRNA",
            ignore_case = TRUE
          )
        ) ~
          
          "IntaRNA",
        
        
        stringr::str_detect(
          method,
          stringr::regex(
            "CopraRNA",
            ignore_case = TRUE
          )
        ) ~
          
          "CopraRNA",
        
        
        TRUE ~
          
          method
      )
  )



# ============================================================
# PREPARE PLOTTING TABLE
# ============================================================

plot_df <- binding |>
  dplyr::mutate(
    
    gene_display =
      dplyr::if_else(
        
        is.na(gene) |
          gene == "",
        
        reference_locus,
        
        gene
      ),
    
    
    binding_left =
      pmin(
        binding_left,
        binding_right,
        na.rm = FALSE
      ),
    
    
    binding_right =
      pmax(
        binding_left,
        binding_right,
        na.rm = FALSE
      ),
    
    
    TSS_marker_class =
      dplyr::case_when(
        
        TSS_support ==
          "Both_concordant" ~
          
          "WT plate + broth",
        
        
        TSS_support %in%
          c(
            "WT_plate_only",
            "WT_broth_only"
          ) ~
          
          "One condition",
        
        
        TRUE ~
          
          NA_character_
      )
  )



# ============================================================
# QC: REMOVE ROWS WITHOUT VALID INTERACTION COORDINATES
# ============================================================

invalid_coordinate_rows <- plot_df |>
  dplyr::filter(
    is.na(binding_left) |
      is.na(binding_right)
  )


if (
  nrow(
    invalid_coordinate_rows
  ) > 0
) {
  
  warning(
    nrow(
      invalid_coordinate_rows
    ),
    " interaction row(s) lack valid plotting coordinates ",
    "and will not be displayed."
  )
}


plot_df <- plot_df |>
  dplyr::filter(
    !is.na(binding_left),
    !is.na(binding_right)
  )



# ============================================================
# ORDER ROWS BY INTERACTION POSITION
# ============================================================
#
# This reproduces the historical figure logic:
#
# most upstream interactions appear together, followed by
# increasingly downstream interactions.

plot_df <- plot_df |>
  dplyr::arrange(
    
    binding_left,
    binding_right,
    gene_display,
    method
  ) |>
  
  dplyr::mutate(
    
    row_id =
      dplyr::row_number()
  )


n_rows <- nrow(
  plot_df
)


plot_df <- plot_df |>
  dplyr::mutate(
    
    y =
      n_rows -
      row_id +
      1
  )



# ============================================================
# DETERMINE PLOTTING RANGE
# ============================================================

x_values <- c(
  
  plot_df$binding_left,
  
  plot_df$binding_right,
  
  plot_df$representative_TSS_rel_start
)


x_values <- x_values[
  is.finite(
    x_values
  )
]


if (length(x_values) == 0) {
  
  stop(
    "No valid transcript-relative coordinates were found."
  )
}



# Right limit derived from observed data.

plot_x_max <-
  ceiling(
    (
      max(x_values) +
        20
    ) /
      50
  ) *
  50


plot_x_max <-
  max(
    plot_x_max,
    minimum_plot_x_max
  )



# Additional space to the left for gene names.

table_space <-
  95


full_x_min <-
  plot_x_min -
  table_space


full_x_max <-
  plot_x_max


x_gene <-
  plot_x_min -
  82



message(
  "Transcript-relative plotting window: ",
  plot_x_min,
  " to ",
  plot_x_max,
  " nt"
)



# ============================================================
# HEADER POSITION
# ============================================================

header_y <-
  n_rows +
  2.4



# ============================================================
# PREPARE TSS MARKERS
# ============================================================

tss_both <- plot_df |>
  dplyr::filter(
    
    TSS_marker_class ==
      "WT plate + broth",
    
    !is.na(
      representative_TSS_rel_start
    )
  )


tss_one <- plot_df |>
  dplyr::filter(
    
    TSS_marker_class ==
      "One condition",
    
    !is.na(
      representative_TSS_rel_start
    )
  )


tick_half_height <-
  0.28



# ============================================================
# TSS LEGEND DATA
# ============================================================

tss_legend_df <- tibble::tibble(
  
  x =
    c(
      NA_real_,
      NA_real_
    ),
  
  y =
    c(
      NA_real_,
      NA_real_
    ),
  
  TSS_legend =
    factor(
      
      c(
        "WT plate + broth",
        "One condition"
      ),
      
      levels =
        c(
          "WT plate + broth",
          "One condition"
        )
    )
)



# ============================================================
# GENERATE FIGURE
# ============================================================

p <- ggplot2::ggplot() +
  
  
  # ----------------------------------------------------------
# Horizontal target rows
# ----------------------------------------------------------

ggplot2::geom_segment(
  
  data =
    plot_df,
  
  ggplot2::aes(
    
    x =
      plot_x_min,
    
    xend =
      plot_x_max,
    
    y =
      y,
    
    yend =
      y
  ),
  
  linewidth =
    0.34,
  
  colour =
    "grey72"
) +
  
  
  # ----------------------------------------------------------
# Subtle highlight around translation start
# ----------------------------------------------------------

ggplot2::annotate(
  
  "rect",
  
  xmin =
    -5,
  
  xmax =
    5,
  
  ymin =
    0.5,
  
  ymax =
    n_rows +
    0.5,
  
  fill =
    "grey60",
  
  alpha =
    0.12
) +
  
  
  # ----------------------------------------------------------
# CDS start
# ----------------------------------------------------------

ggplot2::geom_vline(
  
  xintercept =
    0,
  
  linewidth =
    0.45,
  
  linetype =
    "dashed",
  
  colour =
    "grey35"
) +
  
  
  # ----------------------------------------------------------
# Predicted interaction intervals
# ----------------------------------------------------------

ggplot2::geom_segment(
  
  data =
    plot_df,
  
  ggplot2::aes(
    
    x =
      binding_left,
    
    xend =
      binding_right,
    
    y =
      y,
    
    yend =
      y,
    
    colour =
      method
  ),
  
  linewidth =
    2.5,
  
  lineend =
    "butt"
) +
  
  
  # ----------------------------------------------------------
# Concordant WT plate + broth TSS
#
# Filled vertical tick
# ----------------------------------------------------------

ggplot2::geom_segment(
  
  data =
    tss_both,
  
  ggplot2::aes(
    
    x =
      representative_TSS_rel_start,
    
    xend =
      representative_TSS_rel_start,
    
    y =
      y -
      tick_half_height,
    
    yend =
      y +
      tick_half_height
  ),
  
  linewidth =
    1.25,
  
  colour =
    "black",
  
  show.legend =
    FALSE
) +
  
  
  # ----------------------------------------------------------
# One-condition TSS
#
# Draw black thick line, then narrower white line to
# reproduce the historical open-tick appearance.
# ----------------------------------------------------------

ggplot2::geom_segment(
  
  data =
    tss_one,
  
  ggplot2::aes(
    
    x =
      representative_TSS_rel_start,
    
    xend =
      representative_TSS_rel_start,
    
    y =
      y -
      tick_half_height,
    
    yend =
      y +
      tick_half_height
  ),
  
  linewidth =
    1.65,
  
  colour =
    "black",
  
  show.legend =
    FALSE
) +
  
  
  ggplot2::geom_segment(
    
    data =
      tss_one,
    
    ggplot2::aes(
      
      x =
        representative_TSS_rel_start,
      
      xend =
        representative_TSS_rel_start,
      
      y =
        y -
        tick_half_height,
      
      yend =
        y +
        tick_half_height
    ),
    
    linewidth =
      0.65,
    
    colour =
      "white",
    
    show.legend =
      FALSE
  ) +
  
  
  # ----------------------------------------------------------
# Target names
# ----------------------------------------------------------

ggplot2::geom_text(
  
  data =
    plot_df,
  
  ggplot2::aes(
    
    x =
      x_gene,
    
    y =
      y,
    
    label =
      gene_display
  ),
  
  hjust =
    0,
  
  size =
    4.1,
  
  fontface =
    "italic"
) +
  
  
  # ----------------------------------------------------------
# Target header
# ----------------------------------------------------------

ggplot2::annotate(
  
  "text",
  
  x =
    x_gene,
  
  y =
    header_y,
  
  label =
    "Target",
  
  hjust =
    0,
  
  size =
    4.5,
  
  fontface =
    "bold"
) +
  
  
  # ----------------------------------------------------------
# Region headers
# ----------------------------------------------------------

ggplot2::annotate(
  
  "text",
  
  x =
    mean(
      c(
        plot_x_min,
        0
      )
    ),
  
  y =
    header_y,
  
  label =
    "5' untranslated region",
  
  size =
    4.4
) +
  
  
  ggplot2::annotate(
    
    "text",
    
    x =
      mean(
        c(
          0,
          plot_x_max
        )
      ),
    
    y =
      header_y,
    
    label =
      "Coding sequence",
    
    size =
      4.4
  ) +
  
  
  # ----------------------------------------------------------
# Dummy symbols for TSS legend
# ----------------------------------------------------------

ggplot2::geom_point(
  
  data =
    tss_legend_df,
  
  ggplot2::aes(
    
    x =
      x,
    
    y =
      y,
    
    shape =
      TSS_legend
  ),
  
  colour =
    "black",
  
  size =
    5.0,
  
  stroke =
    1.0,
  
  inherit.aes =
    FALSE
) +
  
  
  # ----------------------------------------------------------
# Prediction-method colours
# ----------------------------------------------------------

ggplot2::scale_colour_manual(
  
  name =
    "Prediction method",
  
  values =
    c(
      
      "CopraRNA" =
        "#F08072",
      
      "IntaRNA" =
        "#00BFC4",
      
      "TargetRNA2" =
        "#7CAE00"
    )
) +
  
  
  # ----------------------------------------------------------
# TSS legend symbols
# ----------------------------------------------------------

ggplot2::scale_shape_manual(
  
  name =
    "TSS support",
  
  values =
    c(
      
      "WT plate + broth" =
        15,
      
      "One condition" =
        0
    )
) +
  
  
  # ----------------------------------------------------------
# X axis
#
# No hard scale limits are applied here because using
# scale_x_continuous(limits = ...) can remove interaction
# segments that extend beyond the plotting window.
#
# coord_cartesian() below performs visual clipping instead.
# ----------------------------------------------------------

ggplot2::scale_x_continuous(
  
  breaks =
    seq(
      plot_x_min,
      plot_x_max,
      by = 50
    ),
  
  minor_breaks =
    seq(
      plot_x_min,
      plot_x_max,
      by = 25
    ),
  
  sec.axis =
    ggplot2::dup_axis(
      
      name =
        NULL,
      
      breaks =
        seq(
          plot_x_min,
          plot_x_max,
          by = 50
        )
    ),
  
  expand =
    c(
      0,
      0
    )
) +
  
  
  # ----------------------------------------------------------
# Y axis
# ----------------------------------------------------------

ggplot2::scale_y_continuous(
  
  limits =
    c(
      0.5,
      n_rows +
        2.9
    ),
  
  breaks =
    NULL,
  
  expand =
    c(
      0,
      0
    )
) +
  
  
  # ----------------------------------------------------------
# Display window
# ----------------------------------------------------------

ggplot2::coord_cartesian(
  
  xlim =
    c(
      full_x_min,
      full_x_max
    ),
  
  clip =
    "off"
) +
  
  
  # ----------------------------------------------------------
# Axis labels
# ----------------------------------------------------------

ggplot2::labs(
  
  x =
    "Position relative to CDS start (nt)",
  
  y =
    NULL
) +
  
  
  # ----------------------------------------------------------
# Theme
# ----------------------------------------------------------

ggplot2::theme_bw(
  base_size =
    11
) +
  
  
  ggplot2::theme(
    
    panel.grid.major.y =
      ggplot2::element_blank(),
    
    panel.grid.minor.y =
      ggplot2::element_blank(),
    
    
    panel.grid.major.x =
      ggplot2::element_line(
        
        colour =
          "grey88",
        
        linewidth =
          0.30
      ),
    
    
    panel.grid.minor.x =
      ggplot2::element_line(
        
        colour =
          "grey94",
        
        linewidth =
          0.22
      ),
    
    
    axis.text.y =
      ggplot2::element_blank(),
    
    axis.ticks.y =
      ggplot2::element_blank(),
    
    
    axis.text.x.bottom =
      ggplot2::element_text(
        size = 10
      ),
    
    
    axis.ticks.x.bottom =
      ggplot2::element_line(
        linewidth = 0.4
      ),
    
    
    axis.text.x.top =
      ggplot2::element_text(
        size = 10
      ),
    
    
    axis.ticks.x.top =
      ggplot2::element_line(
        linewidth = 0.4
      ),
    
    
    axis.title.x =
      ggplot2::element_text(
        size = 12
      ),
    
    
    legend.position =
      "bottom",
    
    legend.box =
      "vertical",
    
    
    legend.title =
      ggplot2::element_text(
        
        face =
          "bold",
        
        size =
          13
      ),
    
    
    legend.text =
      ggplot2::element_text(
        size = 12
      ),
    
    
    legend.key.width =
      grid::unit(
        1.8,
        "cm"
      ),
    
    
    legend.key.height =
      grid::unit(
        0.8,
        "cm"
      ),
    
    
    legend.spacing.y =
      grid::unit(
        0.02,
        "cm"
      ),
    
    
    legend.box.spacing =
      grid::unit(
        0.05,
        "cm"
      ),
    
    
    legend.margin =
      ggplot2::margin(
        0,
        0,
        0,
        0
      ),
    
    
    plot.margin =
      ggplot2::margin(
        
        t = 12,
        r = 12,
        b = 12,
        l = 12
      )
  ) +
  
  
  # ----------------------------------------------------------
# Legends
# ----------------------------------------------------------

ggplot2::guides(
  
  colour =
    ggplot2::guide_legend(
      
      order =
        1,
      
      override.aes =
        list(
          linewidth = 4.5
        )
    ),
  
  
  shape =
    ggplot2::guide_legend(
      
      order =
        2,
      
      override.aes =
        list(
          
          size =
            5.2,
          
          colour =
            "black"
        )
    )
)



# ============================================================
# SAVE FIGURE
# ============================================================

ggplot2::ggsave(
  
  filename =
    pdf_file,
  
  plot =
    p,
  
  width =
    8.6,
  
  height =
    16.5,
  
  units =
    "in",
  
  device =
    cairo_pdf
)



ggplot2::ggsave(
  
  filename =
    png_file,
  
  plot =
    p,
  
  width =
    8.6,
  
  height =
    16.5,
  
  units =
    "in",
  
  dpi =
    600
)



# ============================================================
# EXPORT PLOTTING DATA
# ============================================================

readr::write_csv(
  
  plot_df,
  
  plotting_data_file,
  
  na = ""
)



# ============================================================
# QC SUMMARIES
# ============================================================

method_summary <- plot_df |>
  dplyr::group_by(
    method
  ) |>
  dplyr::summarise(
    
    n_interactions =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  dplyr::arrange(
    method
  )


tss_marker_summary <- plot_df |>
  dplyr::group_by(
    TSS_marker_class
  ) |>
  dplyr::summarise(
    
    n_interactions =
      dplyr::n(),
    
    .groups =
      "drop"
  ) |>
  dplyr::arrange(
    TSS_marker_class
  )


binding_context_summary <- plot_df |>
  dplyr::group_by(
    binding_context
  ) |>
  dplyr::summarise(
    
    n_interactions =
      dplyr::n(),
    
    n_genes =
      dplyr::n_distinct(
        reference_locus
      ),
    
    .groups =
      "drop"
  ) |>
  dplyr::arrange(
    dplyr::desc(
      n_interactions
    )
  )



# ============================================================
# CONSOLE REPORT
# ============================================================

cat(
  "\n",
  "============================================\n",
  "Transcript-relative interaction plot complete\n",
  "============================================\n\n",
  sep = ""
)


cat(
  "Interaction rows plotted: ",
  nrow(plot_df),
  "\n",
  sep = ""
)


cat(
  "Unique target loci: ",
  dplyr::n_distinct(
    plot_df$reference_locus
  ),
  "\n",
  sep = ""
)


cat(
  "WT plate + broth TSS markers: ",
  nrow(tss_both),
  "\n",
  sep = ""
)


cat(
  "One-condition TSS markers: ",
  nrow(tss_one),
  "\n",
  sep = ""
)


cat(
  "Displayed interaction scale: ",
  plot_x_min,
  " to ",
  plot_x_max,
  " nt\n\n",
  sep = ""
)



cat(
  "Interactions by prediction method:\n"
)


print(
  method_summary
)



cat(
  "\nBinding-context QC:\n"
)


print(
  binding_context_summary
)



cat(
  "\nOutputs:\n"
)


cat(
  pdf_file,
  "\n"
)


cat(
  png_file,
  "\n"
)


cat(
  plotting_data_file,
  "\n"
)
