# ============================================================
# 08_prepare_motif_windows.R
#
# Aim
# ---
# Generate strand-aware genomic sequence windows around the
# translation start of:
#
#   1. predicted sRNA target genes;
#   2. non-target background genes.
#
# These sequences are intended for motif analysis in Script 09
# and can also be used as input for MEME-suite tools.
#
#
# WINDOW DEFINITION
# -----------------
#
# Default:
#
#     -200 nt upstream of CDS start
#       through
#     +100 nt downstream of CDS start
#
# Coordinates are defined relative to the translation start:
#
#     -200 ... -1 | 0 | +1 ... +100
#
# giving a 301-nt sequence.
#
# All extracted sequences are oriented in the direction of
# transcription:
#
#     + strand = genomic sequence
#     - strand = reverse complement
#
#
# CANDIDATE SET
# -------------
#
# The candidate FASTA contains the harmonised annotated target
# set generated by Script 01.
#
#
# BACKGROUND SET
# --------------
#
# The background contains all reference genes with valid genomic
# coordinates that are NOT members of the candidate set.
#
# The same sequence window and strand-aware extraction are
# applied to candidates and background genes.
#
#
# INPUTS
# ------
#
# results/tables/
#   target_candidates_annotated.csv
#
# data/reference/
#   reference_gene_coordinates.csv
#
# AND either:
#
# data/reference/
#   reference_genome.fasta
#
# OR:
#
# data/reference/
#   reference_genome.gbff
#
#
# OUTPUTS
# -------
#
# results/motif/
#   candidate_windows_minus200_plus100.fasta
#   background_windows_minus200_plus100.fasta
#
# results/tables/
#   motif_window_metadata.csv
#   motif_window_qc.csv
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()


candidate_file <-
  "results/tables/target_candidates_annotated.csv"


coordinate_file <-
  "data/reference/reference_gene_coordinates.csv"


# Preferred reference sequence.
#
# If this FASTA file does not exist, the script will attempt to
# extract the sequence from reference_genome.gbff instead.

reference_fasta_file <-
  "data/reference/reference_genome.fasta"


reference_gbff_file <-
  "data/reference/reference_genome.gbff"


# Sequence window relative to CDS start.

window_upstream_nt <-
  200L


window_downstream_nt <-
  100L


motif_output_dir <-
  "results/motif"


table_output_dir <-
  "results/tables"



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "stringr",
  "tibble"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  
  install.packages(
    missing_pkgs
  )
}


suppressPackageStartupMessages({
  
  library(readr)
  library(dplyr)
  library(stringr)
  library(tibble)
  
})



# ============================================================
# CREATE OUTPUT DIRECTORIES
# ============================================================

dir.create(
  motif_output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


dir.create(
  table_output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)



# ============================================================
# HELPER: CHECK REQUIRED COLUMNS
# ============================================================

check_columns <- function(
    df,
    required,
    label
) {
  
  missing_columns <- setdiff(
    required,
    names(df)
  )
  
  
  if (length(missing_columns) > 0) {
    
    stop(
      label,
      " is missing required column(s):\n",
      paste(
        missing_columns,
        collapse = ", "
      ),
      "\n\nAvailable columns:\n",
      paste(
        names(df),
        collapse = ", "
      )
    )
  }
}



# ============================================================
# HELPER: REVERSE COMPLEMENT
# ============================================================

reverse_complement <- function(sequence) {
  
  sequence <-
    toupper(sequence)
  
  
  bases <-
    strsplit(
      sequence,
      split = "",
      fixed = TRUE
    )[[1]]
  
  
  complement_table <- c(
    
    "A" = "T",
    "T" = "A",
    "G" = "C",
    "C" = "G",
    
    "N" = "N",
    
    # IUPAC ambiguity codes
    
    "R" = "Y",
    "Y" = "R",
    "S" = "S",
    "W" = "W",
    "K" = "M",
    "M" = "K",
    
    "B" = "V",
    "D" = "H",
    "H" = "D",
    "V" = "B"
  )
  
  
  unknown <-
    !bases %in%
    names(
      complement_table
    )
  
  
  bases[unknown] <-
    "N"
  
  
  complemented <-
    complement_table[
      bases
    ]
  
  
  paste0(
    rev(complemented),
    collapse = ""
  )
}



# ============================================================
# HELPER: READ FASTA
# ============================================================

read_fasta_base <- function(path) {
  
  lines <- readLines(
    path,
    warn = FALSE
  )
  
  
  header_rows <- which(
    startsWith(
      lines,
      ">"
    )
  )
  
  
  if (length(header_rows) == 0) {
    
    stop(
      "No FASTA headers were found in:\n",
      path
    )
  }
  
  
  records <- vector(
    "list",
    length(header_rows)
  )
  
  
  for (
    i in seq_along(
      header_rows
    )
  ) {
    
    start_row <-
      header_rows[i] + 1L
    
    
    if (
      i <
      length(header_rows)
    ) {
      
      end_row <-
        header_rows[i + 1L] - 1L
      
    } else {
      
      end_row <-
        length(lines)
    }
    
    
    sequence_lines <-
      if (
        start_row <= end_row
      ) {
        
        lines[
          start_row:end_row
        ]
        
      } else {
        
        character(0)
      }
    
    
    sequence <-
      paste0(
        sequence_lines,
        collapse = ""
      )
    
    
    sequence <-
      toupper(
        gsub(
          "[^A-Za-z]",
          "",
          sequence
        )
      )
    
    
    header <-
      sub(
        "^>",
        "",
        lines[
          header_rows[i]
        ]
      )
    
    
    record_name <-
      strsplit(
        header,
        "\\s+"
      )[[1]][1]
    
    
    records[[i]] <-
      tibble::tibble(
        
        sequence_name =
          record_name,
        
        sequence =
          sequence,
        
        sequence_length =
          nchar(sequence)
      )
  }
  
  
  dplyr::bind_rows(
    records
  )
}



# ============================================================
# HELPER: READ GENBANK ORIGIN SEQUENCE
# ============================================================
#
# This parser extracts nucleotide sequences from GenBank records.
#
# It is intentionally restricted to the sequence itself; gene
# annotation is taken from reference_gene_coordinates.csv.

read_genbank_sequence <- function(path) {
  
  lines <- readLines(
    path,
    warn = FALSE
  )
  
  
  locus_rows <- which(
    grepl(
      "^LOCUS\\s+",
      lines
    )
  )
  
  
  origin_rows <- which(
    grepl(
      "^ORIGIN",
      lines
    )
  )
  
  
  end_rows <- which(
    grepl(
      "^//",
      lines
    )
  )
  
  
  if (
    length(origin_rows) == 0
  ) {
    
    stop(
      "No ORIGIN section found in GenBank file:\n",
      path
    )
  }
  
  
  if (
    length(origin_rows) !=
    length(end_rows)
  ) {
    
    stop(
      "Could not pair GenBank ORIGIN and // sections."
    )
  }
  
  
  records <- vector(
    "list",
    length(origin_rows)
  )
  
  
  for (
    i in seq_along(
      origin_rows
    )
  ) {
    
    origin <-
      origin_rows[i]
    
    
    record_end <-
      end_rows[
        end_rows > origin
      ][1]
    
    
    sequence_lines <-
      lines[
        (origin + 1L):
          (record_end - 1L)
      ]
    
    
    sequence <-
      paste0(
        sequence_lines,
        collapse = ""
      )
    
    
    sequence <-
      toupper(
        gsub(
          "[^A-Za-z]",
          "",
          sequence
        )
      )
    
    
    previous_locus_rows <-
      locus_rows[
        locus_rows < origin
      ]
    
    
    if (
      length(
        previous_locus_rows
      ) > 0
    ) {
      
      locus_line <-
        lines[
          max(
            previous_locus_rows
          )
        ]
      
      
      fields <-
        strsplit(
          trimws(locus_line),
          "\\s+"
        )[[1]]
      
      
      sequence_name <-
        if (
          length(fields) >= 2
        ) {
          
          fields[2]
          
        } else {
          
          paste0(
            "record_",
            i
          )
        }
      
    } else {
      
      sequence_name <-
        paste0(
          "record_",
          i
        )
    }
    
    
    records[[i]] <-
      tibble::tibble(
        
        sequence_name =
          sequence_name,
        
        sequence =
          sequence,
        
        sequence_length =
          nchar(sequence)
      )
  }
  
  
  dplyr::bind_rows(
    records
  )
}



# ============================================================
# LOAD REFERENCE GENOME
# ============================================================

if (
  file.exists(
    reference_fasta_file
  )
) {
  
  message(
    "Reading reference sequence from FASTA: ",
    reference_fasta_file
  )
  
  
  genome_records <-
    read_fasta_base(
      reference_fasta_file
    )
  
  
} else if (
  file.exists(
    reference_gbff_file
  )
) {
  
  message(
    "Reference FASTA not found."
  )
  
  
  message(
    "Reading reference sequence from GenBank: ",
    reference_gbff_file
  )
  
  
  genome_records <-
    read_genbank_sequence(
      reference_gbff_file
    )
  
  
} else {
  
  stop(
    "No reference genome sequence was found.\n\n",
    "Expected either:\n",
    reference_fasta_file,
    "\nOR\n",
    reference_gbff_file
  )
}



# ============================================================
# CHECK NUMBER OF REFERENCE SEQUENCES
# ============================================================
#
# The current MIDG2331 analysis uses a single complete bacterial
# chromosome.
#
# If applying the pipeline to a multi-contig assembly, the
# coordinate table must also identify the corresponding contig.

if (
  nrow(
    genome_records
  ) != 1
) {
  
  stop(
    "The reference contains ",
    nrow(genome_records),
    " sequence records.\n\n",
    "This version of Script 08 expects a single complete ",
    "reference chromosome. For a multi-contig genome, contig ",
    "identifiers must first be included in ",
    "reference_gene_coordinates.csv."
  )
}



reference_sequence <-
  genome_records$sequence[1]


genome_length <-
  genome_records$sequence_length[1]


reference_sequence_name <-
  genome_records$sequence_name[1]



cat(
  "\nReference sequence: ",
  reference_sequence_name,
  "\n",
  sep = ""
)


cat(
  "Reference length: ",
  genome_length,
  " nt\n",
  sep = ""
)



# ============================================================
# IMPORT REFERENCE GENE COORDINATES
# ============================================================

coordinates <- readr::read_csv(
  coordinate_file,
  show_col_types = FALSE
)


check_columns(
  coordinates,
  c(
    "reference_locus",
    "strand",
    "gene_start",
    "gene_end"
  ),
  "Reference coordinate table"
)



# ============================================================
# STANDARDISE REFERENCE COORDINATES
# ============================================================

coordinates <- coordinates |>
  dplyr::mutate(
    
    reference_locus =
      stringr::str_trim(
        as.character(
          reference_locus
        )
      ),
    
    strand =
      stringr::str_trim(
        as.character(
          strand
        )
      ),
    
    gene_start =
      suppressWarnings(
        as.integer(
          gene_start
        )
      ),
    
    gene_end =
      suppressWarnings(
        as.integer(
          gene_end
        )
      ),
    
    gene_left =
      pmin(
        gene_start,
        gene_end
      ),
    
    gene_right =
      pmax(
        gene_start,
        gene_end
      ),
    
    translation_start =
      dplyr::case_when(
        
        strand == "+" ~
          gene_left,
        
        strand == "-" ~
          gene_right,
        
        TRUE ~
          NA_integer_
      )
  ) |>
  
  dplyr::filter(
    !is.na(reference_locus),
    reference_locus != ""
  ) |>
  
  dplyr::distinct(
    reference_locus,
    .keep_all = TRUE
  )



# ============================================================
# CHECK REFERENCE COORDINATES
# ============================================================

invalid_reference_coordinates <- coordinates |>
  dplyr::filter(
    
    !strand %in%
      c(
        "+",
        "-"
      ) |
      
      is.na(
        translation_start
      ) |
      
      gene_left < 1 |
      
      gene_right >
      genome_length
  )


if (
  nrow(
    invalid_reference_coordinates
  ) > 0
) {
  
  warning(
    nrow(
      invalid_reference_coordinates
    ),
    " reference genes contain invalid genomic coordinates ",
    "and will be excluded."
  )
}


coordinates_valid <- coordinates |>
  dplyr::filter(
    
    strand %in%
      c(
        "+",
        "-"
      ),
    
    !is.na(
      translation_start
    ),
    
    gene_left >= 1,
    
    gene_right <=
      genome_length
  )



# ============================================================
# IMPORT CANDIDATE TARGET SET
# ============================================================

candidates <- readr::read_csv(
  candidate_file,
  show_col_types = FALSE
)


check_columns(
  candidates,
  c(
    "reference_locus",
    "gene",
    "annotation"
  ),
  "Candidate target table"
)



candidates <- candidates |>
  dplyr::mutate(
    
    reference_locus =
      stringr::str_trim(
        as.character(
          reference_locus
        )
      ),
    
    gene =
      stringr::str_trim(
        as.character(
          gene
        )
      ),
    
    annotation =
      as.character(
        annotation
      )
  ) |>
  
  dplyr::filter(
    !is.na(
      reference_locus
    ),
    reference_locus != ""
  ) |>
  
  dplyr::distinct(
    reference_locus,
    .keep_all = TRUE
  )



# ============================================================
# ADD GENE NAMES / ANNOTATION TO REFERENCE TABLE
# ============================================================
#
# reference_gene_coordinates.csv may already contain gene and
# annotation columns.
#
# Where available, preserve these for the background sequences.

if (
  "gene" %in%
  names(
    coordinates_valid
  )
) {
  
  coordinates_valid <-
    coordinates_valid |>
    dplyr::rename(
      reference_gene =
        gene
    )
  
} else {
  
  coordinates_valid$reference_gene <-
    NA_character_
}



if (
  "annotation" %in%
  names(
    coordinates_valid
  )
) {
  
  coordinates_valid <-
    coordinates_valid |>
    dplyr::rename(
      reference_annotation =
        annotation
    )
  
} else {
  
  coordinates_valid$reference_annotation <-
    NA_character_
}



# ============================================================
# DEFINE CANDIDATE / BACKGROUND STATUS
# ============================================================

window_table <- coordinates_valid |>
  dplyr::left_join(
    
    candidates |>
      dplyr::select(
        reference_locus,
        candidate_gene =
          gene,
        candidate_annotation =
          annotation
      ),
    
    by =
      "reference_locus"
  ) |>
  
  dplyr::mutate(
    
    dataset =
      dplyr::if_else(
        
        reference_locus %in%
          candidates$reference_locus,
        
        "candidate",
        
        "background"
      ),
    
    gene =
      dplyr::coalesce(
        candidate_gene,
        reference_gene
      ),
    
    annotation =
      dplyr::coalesce(
        candidate_annotation,
        reference_annotation
      )
  )



# ============================================================
# CHECK THAT ALL CANDIDATES HAVE REFERENCE COORDINATES
# ============================================================

candidate_without_coordinates <- setdiff(
  
  candidates$reference_locus,
  
  window_table$reference_locus
)


if (
  length(
    candidate_without_coordinates
  ) > 0
) {
  
  stop(
    "Candidate loci lacking valid reference coordinates:\n",
    paste(
      candidate_without_coordinates,
      collapse = ", "
    )
  )
}



# ============================================================
# HELPER: CIRCULAR GENOME SUBSEQUENCE
# ============================================================
#
# Bacterial reference genomes are commonly circular.
#
# This permits windows close to coordinate 1 or the end of the
# chromosome to wrap across the origin rather than being
# truncated.

extract_circular_sequence <- function(
    sequence,
    start,
    end
) {
  
  genome_n <-
    nchar(sequence)
  
  
  positions <-
    seq.int(
      start,
      end
    )
  
  
  wrapped_positions <-
    (
      (
        positions -
          1L
      ) %%
        genome_n
    ) +
    1L
  
  
  bases <-
    substring(
      sequence,
      wrapped_positions,
      wrapped_positions
    )
  
  
  paste0(
    bases,
    collapse = ""
  )
}



# ============================================================
# CALCULATE GENOMIC WINDOW COORDINATES
# ============================================================
#
# PLUS STRAND
#
#   genomic:
#
#     translation_start - upstream
#       ...
#     translation_start + downstream
#
#
# MINUS STRAND
#
#   genomic interval is reversed:
#
#     translation_start - downstream
#       ...
#     translation_start + upstream
#
# followed by reverse complementation.

window_table <- window_table |>
  dplyr::mutate(
    
    window_genomic_start =
      dplyr::case_when(
        
        strand == "+" ~
          
          translation_start -
          window_upstream_nt,
        
        
        strand == "-" ~
          
          translation_start -
          window_downstream_nt,
        
        
        TRUE ~
          
          NA_integer_
      ),
    
    
    window_genomic_end =
      dplyr::case_when(
        
        strand == "+" ~
          
          translation_start +
          window_downstream_nt,
        
        
        strand == "-" ~
          
          translation_start +
          window_upstream_nt,
        
        
        TRUE ~
          
          NA_integer_
      ),
    
    
    wraps_origin =
      window_genomic_start < 1 |
      window_genomic_end >
      genome_length
  )



# ============================================================
# EXTRACT STRAND-AWARE WINDOWS
# ============================================================

window_sequences <- vector(
  "character",
  nrow(
    window_table
  )
)


for (
  i in seq_len(
    nrow(
      window_table
    )
  )
) {
  
  genomic_sequence <-
    extract_circular_sequence(
      
      sequence =
        reference_sequence,
      
      start =
        window_table$
        window_genomic_start[i],
      
      end =
        window_table$
        window_genomic_end[i]
    )
  
  
  if (
    window_table$strand[i] ==
    "-"
  ) {
    
    genomic_sequence <-
      reverse_complement(
        genomic_sequence
      )
  }
  
  
  window_sequences[i] <-
    genomic_sequence
}



window_table$sequence <-
  window_sequences



# ============================================================
# EXPECTED WINDOW LENGTH
# ============================================================

expected_window_length <-
  window_upstream_nt +
  window_downstream_nt +
  1L



# ============================================================
# SEQUENCE QC
# ============================================================

window_table <- window_table |>
  dplyr::mutate(
    
    sequence_length =
      nchar(
        sequence
      ),
    
    n_ambiguous =
      stringr::str_count(
        sequence,
        "[^ACGT]"
      ),
    
    ambiguous_fraction =
      n_ambiguous /
      sequence_length,
    
    length_ok =
      sequence_length ==
      expected_window_length,
    
    sequence_ok =
      length_ok &
      sequence_length > 0
  )



# ============================================================
# VERIFY TRANSLATION START POSITION WITHIN WINDOW
# ============================================================
#
# With -200/+100 extraction, CDS position 0 should be nucleotide
# 201 within the oriented sequence.

expected_start_position <-
  window_upstream_nt +
  1L


window_table <-
  window_table |>
  dplyr::mutate(
    
    translation_start_window_position =
      expected_start_position
  )



# ============================================================
# CREATE FASTA-SAFE GENE LABELS
# ============================================================

window_table <- window_table |>
  dplyr::mutate(
    
    gene_display =
      dplyr::if_else(
        
        is.na(gene) |
          gene == "",
        
        reference_locus,
        
        gene
      ),
    
    
    fasta_header =
      paste0(
        
        reference_locus,
        
        "|gene=",
        stringr::str_replace_all(
          gene_display,
          "\\s+",
          "_"
        ),
        
        "|strand=",
        strand,
        
        "|CDS_start=",
        translation_start,
        
        "|window=-",
        window_upstream_nt,
        
        "_+",
        window_downstream_nt
      )
  )



# ============================================================
# SPLIT CANDIDATE AND BACKGROUND
# ============================================================

candidate_windows <- window_table |>
  dplyr::filter(
    dataset ==
      "candidate"
  )


background_windows <- window_table |>
  dplyr::filter(
    dataset ==
      "background"
  )



# ============================================================
# FASTA WRITER
# ============================================================

write_fasta <- function(
    headers,
    sequences,
    path,
    width = 80L
) {
  
  connection <-
    file(
      path,
      open = "w"
    )
  
  
  on.exit(
    close(connection),
    add = TRUE
  )
  
  
  for (
    i in seq_along(
      sequences
    )
  ) {
    
    writeLines(
      paste0(
        ">",
        headers[i]
      ),
      connection
    )
    
    
    sequence <-
      sequences[i]
    
    
    starts <-
      seq(
        1L,
        nchar(sequence),
        by = width
      )
    
    
    sequence_lines <-
      substring(
        
        sequence,
        
        starts,
        
        pmin(
          starts +
            width -
            1L,
          
          nchar(sequence)
        )
      )
    
    
    writeLines(
      sequence_lines,
      connection
    )
  }
}



# ============================================================
# OUTPUT PATHS
# ============================================================

candidate_fasta_file <- file.path(
  motif_output_dir,
  "candidate_windows_minus200_plus100.fasta"
)


background_fasta_file <- file.path(
  motif_output_dir,
  "background_windows_minus200_plus100.fasta"
)


metadata_file <- file.path(
  table_output_dir,
  "motif_window_metadata.csv"
)


qc_file <- file.path(
  table_output_dir,
  "motif_window_qc.csv"
)



# ============================================================
# WRITE FASTA FILES
# ============================================================

write_fasta(
  
  headers =
    candidate_windows$
    fasta_header,
  
  sequences =
    candidate_windows$
    sequence,
  
  path =
    candidate_fasta_file
)



write_fasta(
  
  headers =
    background_windows$
    fasta_header,
  
  sequences =
    background_windows$
    sequence,
  
  path =
    background_fasta_file
)



# ============================================================
# EXPORT METADATA
# ============================================================

metadata_output <- window_table |>
  dplyr::select(
    
    dataset,
    
    reference_locus,
    gene,
    annotation,
    
    strand,
    
    gene_start,
    gene_end,
    
    translation_start,
    
    window_genomic_start,
    window_genomic_end,
    
    wraps_origin,
    
    translation_start_window_position,
    
    sequence_length,
    
    n_ambiguous,
    ambiguous_fraction,
    
    length_ok,
    sequence_ok,
    
    sequence
  ) |>
  
  dplyr::arrange(
    dataset,
    reference_locus
  )


readr::write_csv(
  metadata_output,
  metadata_file,
  na = ""
)



# ============================================================
# QC SUMMARY
# ============================================================

qc_summary <- tibble::tibble(
  
  metric = c(
    
    "reference_genome_length",
    
    "expected_window_length",
    
    "candidate_loci_input",
    
    "candidate_windows_generated",
    
    "background_windows_generated",
    
    "candidate_windows_wrong_length",
    
    "background_windows_wrong_length",
    
    "candidate_windows_with_ambiguous_bases",
    
    "background_windows_with_ambiguous_bases",
    
    "candidate_windows_wrapping_origin",
    
    "background_windows_wrapping_origin"
  ),
  
  
  value = c(
    
    genome_length,
    
    expected_window_length,
    
    nrow(
      candidates
    ),
    
    nrow(
      candidate_windows
    ),
    
    nrow(
      background_windows
    ),
    
    sum(
      !candidate_windows$
        length_ok
    ),
    
    sum(
      !background_windows$
        length_ok
    ),
    
    sum(
      candidate_windows$
        n_ambiguous >
        0
    ),
    
    sum(
      background_windows$
        n_ambiguous >
        0
    ),
    
    sum(
      candidate_windows$
        wraps_origin
    ),
    
    sum(
      background_windows$
        wraps_origin
    )
  )
)



readr::write_csv(
  qc_summary,
  qc_file,
  na = ""
)



# ============================================================
# CONSOLE REPORT
# ============================================================

cat(
  "\n",
  "============================================\n",
  "Motif-window preparation complete\n",
  "============================================\n\n",
  sep = ""
)



cat(
  "Reference: ",
  reference_sequence_name,
  "\n",
  sep = ""
)


cat(
  "Genome length: ",
  genome_length,
  " nt\n\n",
  sep = ""
)



cat(
  "Window definition: -",
  window_upstream_nt,
  " to +",
  window_downstream_nt,
  " nt relative to CDS start\n",
  sep = ""
)


cat(
  "Expected sequence length: ",
  expected_window_length,
  " nt\n",
  sep = ""
)


cat(
  "CDS start position within FASTA sequence: ",
  expected_start_position,
  "\n\n",
  sep = ""
)



cat(
  "Candidate windows: ",
  nrow(
    candidate_windows
  ),
  "\n",
  sep = ""
)


cat(
  "Background windows: ",
  nrow(
    background_windows
  ),
  "\n\n",
  sep = ""
)



cat(
  "Candidate windows with incorrect length: ",
  sum(
    !candidate_windows$
      length_ok
  ),
  "\n",
  sep = ""
)


cat(
  "Background windows with incorrect length: ",
  sum(
    !background_windows$
      length_ok
  ),
  "\n",
  sep = ""
)



cat(
  "Candidate windows containing ambiguous bases: ",
  sum(
    candidate_windows$
      n_ambiguous >
      0
  ),
  "\n",
  sep = ""
)


cat(
  "Background windows containing ambiguous bases: ",
  sum(
    background_windows$
      n_ambiguous >
      0
  ),
  "\n\n",
  sep = ""
)



cat(
  "Outputs:\n",
  candidate_fasta_file,
  "\n",
  background_fasta_file,
  "\n",
  metadata_file,
  "\n",
  qc_file,
  "\n",
  sep = ""
)
