# ============================================================
# 09_targeted_motif_enrichment.R
#
# Aim
# ---
# Test enrichment of a defined target-site motif in predicted
# sRNA target genes relative to a genomic background.
#
#
# DEFAULT MOTIF
# -------------
#
#     AAACACAACAT
#
#
# MOTIF CLASSES
# -------------
#
# The script evaluates:
#
#   1. Exact motif match
#   2. Exactly one mismatch
#   3. Exact or one mismatch (<=1 mismatch)
#
# Matching is based on Hamming distance across the complete
# motif length.
#
#
# IMPORTANT
# ---------
#
# Sequence windows generated by Script 08 are already oriented
# in the direction of transcription.
#
# Therefore the motif is searched directly in the oriented
# target sequence. The reverse-complement motif is NOT searched
# separately.
#
#
# WINDOW COORDINATES
# ------------------
#
# Script 08 generated:
#
#       -200 to +100 nt
#
# relative to the CDS start.
#
# FASTA position:
#
#       201 = CDS-relative position 0
#
# Therefore:
#
#       relative coordinate =
#           FASTA position - 201
#
#
# INPUTS
# ------
#
# results/motif/
#   candidate_windows_minus200_plus100.fasta
#   background_windows_minus200_plus100.fasta
#
# results/tables/
#   motif_window_metadata.csv
#
#
# OUTPUTS
# -------
#
# results/tables/
#
#   motif_occurrences.csv
#   motif_window_summary.csv
#   motif_enrichment_summary.csv
#   motif_position_summary.csv
#   motif_sequence_variant_summary.csv
#   motif_enrichment_qc.csv
#
# ============================================================



# ============================================================
# USER SETTINGS
# ============================================================

# Set the working directory to the root of the analysis project
# before running this script.
#
# Example:
# setwd("/path/to/sRNA-target-pipeline")

project_dir <- getwd()


candidate_fasta_file <-
  "results/motif/candidate_windows_minus200_plus100.fasta"


background_fasta_file <-
  "results/motif/background_windows_minus200_plus100.fasta"


metadata_file <-
  "results/tables/motif_window_metadata.csv"


output_dir <-
  "results/tables"


# ------------------------------------------------------------
# Motif definition
# ------------------------------------------------------------

target_motif <-
  "AAACACAACAT"


# Maximum number of mismatches retained in the occurrence table.
#
# 0 = exact only
# 1 = exact + one mismatch
# 2 = exact + one/two mismatches
#
# For the present analysis we use 1.

max_mismatches <-
  1L


# ------------------------------------------------------------
# Window definition
# ------------------------------------------------------------
#
# This must match Script 08.

window_upstream_nt <-
  200L


window_downstream_nt <-
  100L



# ============================================================
# PACKAGES
# ============================================================

required_pkgs <- c(
  "readr",
  "dplyr",
  "stringr",
  "tibble"
)


missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_pkgs) > 0) {
  
  install.packages(
    missing_pkgs
  )
}


suppressPackageStartupMessages({
  
  library(readr)
  library(dplyr)
  library(stringr)
  library(tibble)
  
})



# ============================================================
# CREATE OUTPUT DIRECTORY
# ============================================================

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)



# ============================================================
# CHECK INPUT FILES
# ============================================================

required_files <- c(
  candidate_fasta_file,
  background_fasta_file,
  metadata_file
)


missing_files <- required_files[
  !file.exists(required_files)
]


if (length(missing_files) > 0) {
  
  stop(
    "Required input file(s) not found:\n",
    paste(
      missing_files,
      collapse = "\n"
    ),
    "\n\nRun Script 08 first."
  )
}



# ============================================================
# HELPER: READ FASTA
# ============================================================

read_fasta <- function(
    path,
    dataset_label
) {
  
  lines <- readLines(
    path,
    warn = FALSE
  )
  
  
  header_rows <- which(
    startsWith(
      lines,
      ">"
    )
  )
  
  
  if (length(header_rows) == 0) {
    
    stop(
      "No FASTA records found in:\n",
      path
    )
  }
  
  
  records <- vector(
    "list",
    length(
      header_rows
    )
  )
  
  
  for (
    i in seq_along(
      header_rows
    )
  ) {
    
    header_row <-
      header_rows[i]
    
    
    start_row <-
      header_row +
      1L
    
    
    if (
      i <
      length(
        header_rows
      )
    ) {
      
      end_row <-
        header_rows[i + 1L] -
        1L
      
    } else {
      
      end_row <-
        length(lines)
    }
    
    
    sequence_lines <-
      if (
        start_row <= end_row
      ) {
        
        lines[
          start_row:end_row
        ]
        
      } else {
        
        character(0)
      }
    
    
    sequence <-
      paste0(
        sequence_lines,
        collapse = ""
      )
    
    
    sequence <-
      toupper(
        gsub(
          "[^A-Za-z]",
          "",
          sequence
        )
      )
    
    
    header <-
      sub(
        "^>",
        "",
        lines[
          header_row
        ]
      )
    
    
    reference_locus <-
      strsplit(
        header,
        "\\|"
      )[[1]][1]
    
    
    records[[i]] <-
      tibble::tibble(
        
        dataset =
          dataset_label,
        
        reference_locus =
          reference_locus,
        
        fasta_header =
          header,
        
        sequence =
          sequence,
        
        sequence_length =
          nchar(
            sequence
          )
      )
  }
  
  
  dplyr::bind_rows(
    records
  )
}



# ============================================================
# IMPORT FASTA FILES
# ============================================================

candidate_fasta <- read_fasta(
  candidate_fasta_file,
  "candidate"
)


background_fasta <- read_fasta(
  background_fasta_file,
  "background"
)


fasta <- dplyr::bind_rows(
  candidate_fasta,
  background_fasta
)



# ============================================================
# IMPORT METADATA
# ============================================================

metadata <- readr::read_csv(
  metadata_file,
  show_col_types = FALSE
)



required_metadata_cols <- c(
  "dataset",
  "reference_locus",
  "gene",
  "annotation",
  "strand",
  "translation_start",
  "sequence_length",
  "sequence"
)


missing_metadata_cols <- setdiff(
  required_metadata_cols,
  names(metadata)
)


if (
  length(
    missing_metadata_cols
  ) > 0
) {
  
  stop(
    "motif_window_metadata.csv is missing required column(s):\n",
    paste(
      missing_metadata_cols,
      collapse = ", "
    )
  )
}



# ============================================================
# STANDARDISE METADATA
# ============================================================

metadata <- metadata |>
  dplyr::mutate(
    
    dataset =
      as.character(
        dataset
      ),
    
    reference_locus =
      stringr::str_trim(
        as.character(
          reference_locus
        )
      ),
    
    gene =
      stringr::str_trim(
        as.character(
          gene
        )
      ),
    
    sequence =
      toupper(
        as.character(
          sequence
        )
      )
  )



# ============================================================
# FASTA / METADATA QC
# ============================================================

fasta_metadata_check <- fasta |>
  dplyr::left_join(
    
    metadata |>
      dplyr::select(
        
        dataset,
        reference_locus,
        
        metadata_sequence =
          sequence
      ),
    
    by =
      c(
        "dataset",
        "reference_locus"
      )
  ) |>
  
  dplyr::mutate(
    
    sequence_match =
      sequence ==
      metadata_sequence
  )



if (
  any(
    is.na(
      fasta_metadata_check$
      metadata_sequence
    )
  )
) {
  
  stop(
    "At least one FASTA record is absent from ",
    "motif_window_metadata.csv."
  )
}



if (
  any(
    !fasta_metadata_check$
    sequence_match
  )
) {
  
  stop(
    "FASTA sequences and motif_window_metadata.csv ",
    "do not agree."
  )
}



# ============================================================
# MOTIF VALIDATION
# ============================================================

target_motif <-
  toupper(
    target_motif
  )


if (
  !grepl(
    "^[ACGT]+$",
    target_motif
  )
) {
  
  stop(
    "target_motif must contain only A, C, G and T."
  )
}


motif_length <-
  nchar(
    target_motif
  )


expected_window_length <-
  window_upstream_nt +
  window_downstream_nt +
  1L


cds_start_sequence_position <-
  window_upstream_nt +
  1L



# ============================================================
# HELPER: HAMMING DISTANCE
# ============================================================

hamming_distance <- function(
    x,
    motif
) {
  
  x_chars <-
    strsplit(
      x,
      "",
      fixed = TRUE
    )[[1]]
  
  
  motif_chars <-
    strsplit(
      motif,
      "",
      fixed = TRUE
    )[[1]]
  
  
  if (
    length(
      x_chars
    ) !=
    length(
      motif_chars
    )
  ) {
    
    stop(
      "Hamming-distance sequences must have equal length."
    )
  }
  
  
  sum(
    x_chars !=
      motif_chars
  )
}



# ============================================================
# HELPER: FIND MOTIF OCCURRENCES
# ============================================================

find_motif_occurrences <- function(
    sequence,
    motif,
    maximum_mismatches
) {
  
  sequence <-
    toupper(
      sequence
    )
  
  
  motif <-
    toupper(
      motif
    )
  
  
  sequence_length <-
    nchar(
      sequence
    )
  
  
  motif_length <-
    nchar(
      motif
    )
  
  
  if (
    sequence_length <
    motif_length
  ) {
    
    return(
      tibble::tibble()
    )
  }
  
  
  starts <-
    seq_len(
      sequence_length -
        motif_length +
        1L
    )
  
  
  out <- vector(
    "list",
    length(
      starts
    )
  )
  
  
  k <- 0L
  
  
  for (
    start_position in starts
  ) {
    
    end_position <-
      start_position +
      motif_length -
      1L
    
    
    observed <-
      substr(
        sequence,
        start_position,
        end_position
      )
    
    
    # Ignore windows containing ambiguous bases.
    
    if (
      !grepl(
        "^[ACGT]+$",
        observed
      )
    ) {
      
      next
    }
    
    
    mismatches <-
      hamming_distance(
        observed,
        motif
      )
    
    
    if (
      mismatches <=
      maximum_mismatches
    ) {
      
      k <- k + 1L
      
      
      out[[k]] <-
        tibble::tibble(
          
          sequence_start =
            start_position,
          
          sequence_end =
            end_position,
          
          matched_sequence =
            observed,
          
          n_mismatches =
            mismatches
        )
    }
  }
  
  
  if (
    k == 0L
  ) {
    
    return(
      tibble::tibble()
    )
  }
  
  
  dplyr::bind_rows(
    out[
      seq_len(k)
    ]
  )
}



# ============================================================
# SEARCH ALL WINDOWS
# ============================================================

occurrence_list <- vector(
  "list",
  nrow(
    metadata
  )
)


for (
  i in seq_len(
    nrow(
      metadata
    )
  )
) {
  
  matches <- find_motif_occurrences(
    
    sequence =
      metadata$sequence[i],
    
    motif =
      target_motif,
    
    maximum_mismatches =
      max_mismatches
  )
  
  
  if (
    nrow(matches) == 0
  ) {
    
    occurrence_list[[i]] <-
      NULL
    
    next
  }
  
  
  occurrence_list[[i]] <-
    matches |>
    dplyr::mutate(
      
      dataset =
        metadata$dataset[i],
      
      reference_locus =
        metadata$
        reference_locus[i],
      
      gene =
        metadata$gene[i],
      
      annotation =
        metadata$annotation[i],
      
      strand =
        metadata$strand[i],
      
      .before = 1
    )
}



motif_occurrences <- dplyr::bind_rows(
  occurrence_list
)



# ============================================================
# ADD CDS-RELATIVE MOTIF COORDINATES
# ============================================================

if (
  nrow(
    motif_occurrences
  ) > 0
) {
  
  motif_occurrences <- motif_occurrences |>
    dplyr::mutate(
      
      motif_start_rel_CDS =
        sequence_start -
        cds_start_sequence_position,
      
      motif_end_rel_CDS =
        sequence_end -
        cds_start_sequence_position,
      
      
      match_class =
        dplyr::case_when(
          
          n_mismatches ==
            0L ~
            
            "exact",
          
          
          n_mismatches ==
            1L ~
            
            "one_mismatch",
          
          
          TRUE ~
            
            paste0(
              n_mismatches,
              "_mismatches"
            )
        ),
      
      
      motif_region =
        dplyr::case_when(
          
          motif_end_rel_CDS < 0 ~
            
            "upstream",
          
          
          motif_start_rel_CDS <= 0 &
            motif_end_rel_CDS >= 0 ~
            
            "overlaps_CDS_start",
          
          
          motif_start_rel_CDS > 0 ~
            
            "CDS",
          
          
          TRUE ~
            
            "other"
        )
    )
}



# ============================================================
# WINDOW-LEVEL SUMMARY
# ============================================================
#
# One row per gene/window.
#
# Enrichment tests are performed at this level so a gene with
# several motif occurrences is counted only once.

if (
  nrow(
    motif_occurrences
  ) > 0
) {
  
  occurrence_gene_summary <- motif_occurrences |>
    dplyr::group_by(
      dataset,
      reference_locus
    ) |>
    
    dplyr::summarise(
      
      n_motif_occurrences =
        dplyr::n(),
      
      minimum_mismatches =
        min(
          n_mismatches
        ),
      
      has_exact_motif =
        any(
          n_mismatches ==
            0L
        ),
      
      has_one_mismatch_motif =
        any(
          n_mismatches ==
            1L
        ),
      
      has_leq1_mismatch_motif =
        any(
          n_mismatches <=
            1L
        ),
      
      closest_motif_start_rel_CDS =
        motif_start_rel_CDS[
          which.min(
            abs(
              motif_start_rel_CDS
            )
          )
        ],
      
      .groups =
        "drop"
    )
  
} else {
  
  occurrence_gene_summary <-
    tibble::tibble(
      
      dataset =
        character(),
      
      reference_locus =
        character(),
      
      n_motif_occurrences =
        integer(),
      
      minimum_mismatches =
        integer(),
      
      has_exact_motif =
        logical(),
      
      has_one_mismatch_motif =
        logical(),
      
      has_leq1_mismatch_motif =
        logical(),
      
      closest_motif_start_rel_CDS =
        integer()
    )
}



motif_window_summary <- metadata |>
  dplyr::select(
    
    dataset,
    reference_locus,
    gene,
    annotation,
    strand,
    translation_start
    
  ) |>
  
  dplyr::left_join(
    
    occurrence_gene_summary,
    
    by =
      c(
        "dataset",
        "reference_locus"
      )
  ) |>
  
  dplyr::mutate(
    
    n_motif_occurrences =
      dplyr::coalesce(
        n_motif_occurrences,
        0L
      ),
    
    has_exact_motif =
      dplyr::coalesce(
        has_exact_motif,
        FALSE
      ),
    
    has_one_mismatch_motif =
      dplyr::coalesce(
        has_one_mismatch_motif,
        FALSE
      ),
    
    has_leq1_mismatch_motif =
      dplyr::coalesce(
        has_leq1_mismatch_motif,
        FALSE
      )
  )



# ============================================================
# HELPER: FISHER ENRICHMENT TEST
# ============================================================

run_enrichment_test <- function(
    window_table,
    flag_column,
    label
) {
  
  candidate_data <-
    window_table |>
    dplyr::filter(
      dataset ==
        "candidate"
    )
  
  
  background_data <-
    window_table |>
    dplyr::filter(
      dataset ==
        "background"
    )
  
  
  candidate_positive <-
    sum(
      candidate_data[[flag_column]],
      na.rm = TRUE
    )
  
  
  candidate_negative <-
    nrow(
      candidate_data
    ) -
    candidate_positive
  
  
  background_positive <-
    sum(
      background_data[[flag_column]],
      na.rm = TRUE
    )
  
  
  background_negative <-
    nrow(
      background_data
    ) -
    background_positive
  
  
  contingency <- matrix(
    
    c(
      candidate_positive,
      candidate_negative,
      background_positive,
      background_negative
    ),
    
    nrow = 2,
    
    byrow = TRUE,
    
    dimnames =
      list(
        
        Dataset =
          c(
            "Candidate",
            "Background"
          ),
        
        Motif =
          c(
            "Present",
            "Absent"
          )
      )
  )
  
  
  fisher_result <-
    fisher.test(
      contingency,
      alternative =
        "greater"
    )
  
  
  candidate_fraction <-
    candidate_positive /
    nrow(
      candidate_data
    )
  
  
  background_fraction <-
    background_positive /
    nrow(
      background_data
    )
  
  
  fold_enrichment <-
    if (
      background_fraction >
      0
    ) {
      
      candidate_fraction /
        background_fraction
      
    } else {
      
      Inf
    }
  
  
  tibble::tibble(
    
    motif_test =
      label,
    
    candidate_total =
      nrow(
        candidate_data
      ),
    
    candidate_with_motif =
      candidate_positive,
    
    candidate_fraction =
      candidate_fraction,
    
    background_total =
      nrow(
        background_data
      ),
    
    background_with_motif =
      background_positive,
    
    background_fraction =
      background_fraction,
    
    fold_enrichment =
      fold_enrichment,
    
    odds_ratio =
      unname(
        fisher_result$
          estimate
      ),
    
    odds_ratio_CI_low =
      unname(
        fisher_result$
          conf.int[1]
      ),
    
    odds_ratio_CI_high =
      unname(
        fisher_result$
          conf.int[2]
      ),
    
    fisher_p_value =
      fisher_result$
      p.value
  )
}



# ============================================================
# ENRICHMENT TESTS
# ============================================================

exact_enrichment <- run_enrichment_test(
  
  motif_window_summary,
  
  "has_exact_motif",
  
  "Exact motif"
)



one_mismatch_enrichment <- run_enrichment_test(
  
  motif_window_summary,
  
  "has_one_mismatch_motif",
  
  "Exactly one mismatch"
)



leq1_enrichment <- run_enrichment_test(
  
  motif_window_summary,
  
  "has_leq1_mismatch_motif",
  
  "Exact or one mismatch"
)



motif_enrichment_summary <- dplyr::bind_rows(
  
  exact_enrichment,
  
  one_mismatch_enrichment,
  
  leq1_enrichment
  
) |>
  
  dplyr::mutate(
    
    BH_adjusted_p_value =
      p.adjust(
        fisher_p_value,
        method =
          "BH"
      )
  )



# ============================================================
# POSITION SUMMARY
# ============================================================
#
# Descriptive only.
#
# Positions are reported separately for candidate and
# background occurrences and by mismatch class.

if (
  nrow(
    motif_occurrences
  ) > 0
) {
  
  motif_position_summary <- motif_occurrences |>
    dplyr::group_by(
      dataset,
      match_class,
      motif_region
    ) |>
    
    dplyr::summarise(
      
      n_occurrences =
        dplyr::n(),
      
      n_genes =
        dplyr::n_distinct(
          reference_locus
        ),
      
      median_start_rel_CDS =
        median(
          motif_start_rel_CDS
        ),
      
      minimum_start_rel_CDS =
        min(
          motif_start_rel_CDS
        ),
      
      maximum_start_rel_CDS =
        max(
          motif_start_rel_CDS
        ),
      
      .groups =
        "drop"
    )
  
} else {
  
  motif_position_summary <-
    tibble::tibble()
}



# ============================================================
# SEQUENCE-VARIANT SUMMARY
# ============================================================
#
# Useful for identifying which one-mismatch forms are most
# frequently observed rather than treating all possible
# mismatch variants as equivalent.

if (
  nrow(
    motif_occurrences
  ) > 0
) {
  
  motif_sequence_variant_summary <- motif_occurrences |>
    dplyr::group_by(
      
      matched_sequence,
      n_mismatches
      
    ) |>
    
    dplyr::summarise(
      
      candidate_occurrences =
        sum(
          dataset ==
            "candidate"
        ),
      
      candidate_genes =
        dplyr::n_distinct(
          reference_locus[
            dataset ==
              "candidate"
          ]
        ),
      
      background_occurrences =
        sum(
          dataset ==
            "background"
        ),
      
      background_genes =
        dplyr::n_distinct(
          reference_locus[
            dataset ==
              "background"
          ]
        ),
      
      .groups =
        "drop"
    ) |>
    
    dplyr::arrange(
      
      n_mismatches,
      
      dplyr::desc(
        candidate_genes
      ),
      
      dplyr::desc(
        candidate_occurrences
      ),
      
      matched_sequence
    )
  
} else {
  
  motif_sequence_variant_summary <-
    tibble::tibble()
}



# ============================================================
# QC SUMMARY
# ============================================================

candidate_windows <-
  motif_window_summary |>
  dplyr::filter(
    dataset ==
      "candidate"
  )


background_windows <-
  motif_window_summary |>
  dplyr::filter(
    dataset ==
      "background"
  )


qc_summary <- tibble::tibble(
  
  metric = c(
    
    "motif",
    
    "motif_length",
    
    "maximum_mismatches_tested",
    
    "expected_window_length",
    
    "candidate_windows",
    
    "background_windows",
    
    "candidate_exact_motif",
    
    "background_exact_motif",
    
    "candidate_one_mismatch",
    
    "background_one_mismatch",
    
    "candidate_exact_or_one_mismatch",
    
    "background_exact_or_one_mismatch",
    
    "total_occurrences_retained"
  ),
  
  
  value = c(
    
    target_motif,
    
    motif_length,
    
    max_mismatches,
    
    expected_window_length,
    
    nrow(
      candidate_windows
    ),
    
    nrow(
      background_windows
    ),
    
    sum(
      candidate_windows$
        has_exact_motif
    ),
    
    sum(
      background_windows$
        has_exact_motif
    ),
    
    sum(
      candidate_windows$
        has_one_mismatch_motif
    ),
    
    sum(
      background_windows$
        has_one_mismatch_motif
    ),
    
    sum(
      candidate_windows$
        has_leq1_mismatch_motif
    ),
    
    sum(
      background_windows$
        has_leq1_mismatch_motif
    ),
    
    nrow(
      motif_occurrences
    )
  )
)



# ============================================================
# OUTPUT PATHS
# ============================================================

occurrence_file <- file.path(
  output_dir,
  "motif_occurrences.csv"
)


window_summary_file <- file.path(
  output_dir,
  "motif_window_summary.csv"
)


enrichment_file <- file.path(
  output_dir,
  "motif_enrichment_summary.csv"
)


position_file <- file.path(
  output_dir,
  "motif_position_summary.csv"
)


variant_file <- file.path(
  output_dir,
  "motif_sequence_variant_summary.csv"
)


qc_file <- file.path(
  output_dir,
  "motif_enrichment_qc.csv"
)



# ============================================================
# EXPORT
# ============================================================

readr::write_csv(
  motif_occurrences,
  occurrence_file,
  na = ""
)


readr::write_csv(
  motif_window_summary,
  window_summary_file,
  na = ""
)


readr::write_csv(
  motif_enrichment_summary,
  enrichment_file,
  na = ""
)


readr::write_csv(
  motif_position_summary,
  position_file,
  na = ""
)


readr::write_csv(
  motif_sequence_variant_summary,
  variant_file,
  na = ""
)


readr::write_csv(
  qc_summary,
  qc_file,
  na = ""
)



# ============================================================
# CONSOLE REPORT
# ============================================================

cat(
  "\n",
  "============================================\n",
  "Targeted motif enrichment complete\n",
  "============================================\n\n",
  sep = ""
)



cat(
  "Target motif: ",
  target_motif,
  "\n",
  sep = ""
)


cat(
  "Motif length: ",
  motif_length,
  " nt\n",
  sep = ""
)


cat(
  "Maximum mismatches searched: ",
  max_mismatches,
  "\n\n",
  sep = ""
)



cat(
  "Candidate windows: ",
  nrow(
    candidate_windows
  ),
  "\n",
  sep = ""
)


cat(
  "Background windows: ",
  nrow(
    background_windows
  ),
  "\n\n",
  sep = ""
)



cat(
  "Motif enrichment tests:\n"
)


print(
  motif_enrichment_summary
)



cat(
  "\nCandidate motif counts:\n"
)


cat(
  "Exact motif: ",
  sum(
    candidate_windows$
      has_exact_motif
  ),
  "\n",
  sep = ""
)


cat(
  "Exactly one mismatch: ",
  sum(
    candidate_windows$
      has_one_mismatch_motif
  ),
  "\n",
  sep = ""
)


cat(
  "Exact or one mismatch: ",
  sum(
    candidate_windows$
      has_leq1_mismatch_motif
  ),
  "\n\n",
  sep = ""
)



cat(
  "Background motif counts:\n"
)


cat(
  "Exact motif: ",
  sum(
    background_windows$
      has_exact_motif
  ),
  "\n",
  sep = ""
)


cat(
  "Exactly one mismatch: ",
  sum(
    background_windows$
      has_one_mismatch_motif
  ),
  "\n",
  sep = ""
)


cat(
  "Exact or one mismatch: ",
  sum(
    background_windows$
      has_leq1_mismatch_motif
  ),
  "\n\n",
  sep = ""
)



cat(
  "Outputs:\n",
  occurrence_file,
  "\n",
  window_summary_file,
  "\n",
  enrichment_file,
  "\n",
  position_file,
  "\n",
  variant_file,
  "\n",
  qc_file,
  "\n",
  sep = ""
)
